#!/bin/sh
#
# This script must be run as root
#

myID=`id -u`
if [ "$myID" != "0" ]; then
  echo "This script must be run by root"
  exit 1
fi

if [ "$1" = "" ]; then
	echo ''
	echo "$0 P | p | S | s"
	echo "  where"
	echo "    P/p = P3 Primary"
	echo "    S/s = P3 Secondary"
	echo ''
	exit 1
elif [ "$1" = "p" ] || [ "$1" = "P" ]; then
	modprobe p3primary
	sleep 1
	/usr/sbin/p3sysprimary &
elif [ "$1" = "s" ] || [ "$1" = "S" ]; then
	modprobe p3secondary
	sleep 1
	/usr/sbin/p3syssecondary &
fi

