#!/bin/sh
#
# This script must be run as root
#

myID=`id -u`
if [ "$myID" != "0" ]; then
  echo "This script must be run by root"
  exit 1
fi

if [ "$1" = "" ]; then
	echo ''
	echo "$0 P | p | S | s"
	echo "  where"
	echo "    P/p = P3 Primary"
	echo "    S/s = P3 Secondary"
	echo ''
	exit 1
elif [ "$1" = "p" ] || [ "$1" = "P" ]; then
	PID=`ps -C p3sysprimary -o pid | grep -v PID`
	if [ "$PID" != "" ]; then
		kill $PID
	fi
	rmmod p3primary
elif [ "$1" = "s" ] || [ "$1" = "S" ]; then
	PID=`ps -C p3syssecondary -o pid | grep -v PID`
	if [ "$PID" != "" ]; then
		kill $PID
	fi
	rmmod p3secondary
fi

