Velocite Systems Protected Point to Point Solution: aes_cmac.h File Reference
aes_cmac.h File Reference
Detailed Description
AES developer API header. This header file contains definitions, enumerations, structures, and function declarations used for AES encryption and decryption.
Since:
3.0.6
Version:
5.0.5 and later
! Flags There are no flag dependencies to enable the functions in this header file.
! External Functions This file contains the following public ($extern$) function declarations:
AESCMAC_init
AESCMAC_update
AESCMAC_final
Data Structures
struct AES_OMAC_Ctx
struct AESCMAC_Ctx
Defines
#define CMAC_RESULT_SIZE AES_BLOCK_SIZE
Functions
MOC_EXTERN MSTATUS AESCMAC_init (MOC_SYM(hwAccelDescr hwAccelCtx) const ubyte *keyMaterial, sbyte4 keyLength, AESCMAC_Ctx *pCtx)
MOC_EXTERN MSTATUS AESCMAC_update (MOC_SYM(hwAccelDescr hwAccelCtx) const ubyte *data, sbyte4 dataLength, AESCMAC_Ctx *pCtx)
MOC_EXTERN MSTATUS AESCMAC_final (MOC_SYM(hwAccelDescr hwAccelCtx) ubyte cmac[CMAC_RESULT_SIZE], AESCMAC_Ctx *pCtx)
MOC_EXTERN MSTATUS AES_OMAC_init (AES_OMAC_Ctx *pOMACCtx)
MOC_EXTERN MSTATUS AES_OMAC_update (MOC_SYM(hwAccelDescr hwAccelCtx) aesCipherContext *pAESCtx, AES_OMAC_Ctx *pOMACCtx, const ubyte *data, sbyte4 dataLength)
MOC_EXTERN MSTATUS AES_OMAC_final (MOC_SYM(hwAccelDescr hwAccelCtx) aesCipherContext *pAESCtx, AES_OMAC_Ctx *pOMACCtx, ubyte cmac[CMAC_RESULT_SIZE])
Define Documentation
#define CMAC_RESULT_SIZE AES_BLOCK_SIZE
Referenced by AES_EAX_final(), and AES_EAX_generateTag().
Function Documentation
MOC_EXTERN MSTATUS AESCMAC_init (MOC_SYM(hwAccelDescr hwAccelCtx) const ubyte * keyMaterial, sbyte4 keyLength, AESCMAC_Ctx * pCtx)
References AES_OMAC_init(), AESALGO_makeAesKey(), AESCMAC_Ctx::aesCtx, MODE_CBC, MSTATUS, and AESCMAC_Ctx::omacCtx.
MOC_EXTERN MSTATUS AESCMAC_update (MOC_SYM(hwAccelDescr hwAccelCtx) const ubyte * data, sbyte4 dataLength, AESCMAC_Ctx * pCtx)
References AES_OMAC_update(), AESCMAC_Ctx::aesCtx, MOC_SYM, and AESCMAC_Ctx::omacCtx.
MOC_EXTERN MSTATUS AESCMAC_final (MOC_SYM(hwAccelDescr hwAccelCtx) ubyte cmac[CMAC_RESULT_SIZE], AESCMAC_Ctx * pCtx)
References AES_OMAC_final(), AESCMAC_Ctx::aesCtx, MOC_SYM, and AESCMAC_Ctx::omacCtx.
MOC_EXTERN MSTATUS AES_OMAC_init (AES_OMAC_Ctx * pOMACCtx)
References AES_OMAC_Ctx::currBlock, and AES_OMAC_Ctx::pendingLen.
Referenced by AESCMAC_init().
MOC_EXTERN MSTATUS AES_OMAC_update (MOC_SYM(hwAccelDescr hwAccelCtx) aesCipherContext * pAESCtx, AES_OMAC_Ctx * pOMACCtx, const ubyte * data, sbyte4 dataLength)
References aesEncrypt(), AES_OMAC_Ctx::currBlock, AES_OMAC_Ctx::pending, and AES_OMAC_Ctx::pendingLen.
Referenced by AES_EAX_encryptMessage(), AES_EAX_generateTag(), AES_EAX_init(), AES_EAX_updateHeader(), and AESCMAC_update().
MOC_EXTERN MSTATUS AES_OMAC_final (MOC_SYM(hwAccelDescr hwAccelCtx) aesCipherContext * pAESCtx, AES_OMAC_Ctx * pOMACCtx, ubyte cmac[CMAC_RESULT_SIZE])
References aesEncrypt(), AES_OMAC_Ctx::currBlock, AES_OMAC_Ctx::pending, and AES_OMAC_Ctx::pendingLen.
Referenced by AES_EAX_final(), AES_EAX_generateTag(), AES_EAX_init(), and AESCMAC_final().