Velocite Systems Protected Point to Point Solution: aes_ecb.c File Reference
aes_ecb.c File Reference
#include "../common/moptions.h"
#include "../common/mtypes.h"
#include "../common/mocana.h"
#include "../crypto/hw_accel.h"
#include "../common/mdefs.h"
#include "../common/merrors.h"
#include "../common/mrtos.h"
#include "../common/mstdlib.h"
#include "../common/debug_console.h"
#include "../crypto/aesalgo.h"
#include "../crypto/aes.h"
#include "../crypto/aes_ecb.h"
Functions
BulkCtx CreateAESECBCtx (MOC_SYM(hwAccelDescr hwAccelCtx) ubyte *keyMaterial, sbyte4 keyLength, sbyte4 encrypt)
MSTATUS DeleteAESECBCtx (MOC_SYM(hwAccelDescr hwAccelCtx) BulkCtx *ctx)
MSTATUS DoAESECB (MOC_SYM(hwAccelDescr hwAccelCtx) BulkCtx ctx, ubyte *data, sbyte4 dataLength, sbyte4 encrypt, ubyte *iv)
Function Documentation
BulkCtx CreateAESECBCtx (MOC_SYM(hwAccelDescr hwAccelCtx) ubyte * keyMaterial, sbyte4 keyLength, sbyte4 encrypt)
References AESALGO_makeAesKey(), FREE, MALLOC, MODE_ECB, and NULL.
MSTATUS DeleteAESECBCtx (MOC_SYM(hwAccelDescr hwAccelCtx) BulkCtx * ctx)
References FREE, and NULL.
MSTATUS DoAESECB (MOC_SYM(hwAccelDescr hwAccelCtx) BulkCtx ctx, ubyte * data, sbyte4 dataLength, sbyte4 encrypt, ubyte * iv)
References AES_BLOCK_SIZE, AESALGO_blockDecrypt(), AESALGO_blockEncrypt(), DEBUG_ERROR, DEBUG_SSL_TRANSPORT, and MSTATUS.