Velocite Systems Protected Point to Point Solution: aes_xcbc_mac_96.h File Reference
aes_xcbc_mac_96.h File Reference
Data Structures
struct AES_XCBC_MAC_96_Ctx
Defines
#define AES_XCBC_MAC_96_RESULT_SIZE (12)
#define AES_XCBC_PRF_128_RESULT_SIZE (AES_BLOCK_SIZE)
#define AES_XCBC_PRF_128_update AES_XCBC_MAC_96_update
Typedefs
typedef struct AES_XCBC_MAC_96_Ctx AES_XCBC_PRF_128_Ctx
Functions
MOC_EXTERN MSTATUS AES_XCBC_MAC_96_init (MOC_SYM(hwAccelDescr hwAccelCtx) const ubyte keyMaterial[AES_BLOCK_SIZE], AES_XCBC_MAC_96_Ctx *pCtx)
MOC_EXTERN MSTATUS AES_XCBC_MAC_96_update (MOC_SYM(hwAccelDescr hwAccelCtx) const ubyte *data, sbyte4 dataLength, AES_XCBC_MAC_96_Ctx *pCtx)
MOC_EXTERN MSTATUS AES_XCBC_MAC_96_final (MOC_SYM(hwAccelDescr hwAccelCtx) ubyte cmac[AES_XCBC_MAC_96_RESULT_SIZE], AES_XCBC_MAC_96_Ctx *pCtx)
MOC_EXTERN MSTATUS AES_XCBC_PRF_128_init (MOC_SYM(hwAccelDescr hwAccelCtx) const ubyte keyMaterial[], sbyte4 keyLength, AES_XCBC_PRF_128_Ctx *pCtx)
MOC_EXTERN MSTATUS AES_XCBC_PRF_128_update (MOC_SYM(hwAccelDescr hwAccelCtx) const ubyte *data, sbyte4 dataLength, AES_XCBC_PRF_128_Ctx *pCtx)
MOC_EXTERN MSTATUS AES_XCBC_PRF_128_final (MOC_SYM(hwAccelDescr hwAccelCtx) ubyte cmac[AES_XCBC_PRF_128_RESULT_SIZE], AES_XCBC_PRF_128_Ctx *pCtx)
Define Documentation
#define AES_XCBC_MAC_96_RESULT_SIZE (12)
#define AES_XCBC_PRF_128_RESULT_SIZE (AES_BLOCK_SIZE)
#define AES_XCBC_PRF_128_update AES_XCBC_MAC_96_update
Referenced by AES_XCBC_PRF_128_init().
Typedef Documentation
typedef struct AES_XCBC_MAC_96_Ctx AES_XCBC_PRF_128_Ctx
Function Documentation
MOC_EXTERN MSTATUS AES_XCBC_MAC_96_init (MOC_SYM(hwAccelDescr hwAccelCtx) const ubyte keyMaterial[AES_BLOCK_SIZE], AES_XCBC_MAC_96_Ctx * pCtx)
References AESALGO_makeAesKey(), AES_XCBC_MAC_96_Ctx::aesCtx, AES_XCBC_MAC_96_Ctx::currBlock, AES_XCBC_MAC_96_Ctx::keyAesCtx, MODE_CBC, MSTATUS, and AES_XCBC_MAC_96_Ctx::pendingLen.
Referenced by AES_XCBC_PRF_128_init().
MOC_EXTERN MSTATUS AES_XCBC_MAC_96_update (MOC_SYM(hwAccelDescr hwAccelCtx) const ubyte * data, sbyte4 dataLength, AES_XCBC_MAC_96_Ctx * pCtx)
References AES_BLOCK_SIZE, AES_XCBC_MAC_96_Ctx::aesCtx, aesEncrypt(), AES_XCBC_MAC_96_Ctx::currBlock, aesCipherContext::Nr, AES_XCBC_MAC_96_Ctx::pending, AES_XCBC_MAC_96_Ctx::pendingLen, and aesCipherContext::rk.
MOC_EXTERN MSTATUS AES_XCBC_MAC_96_final (MOC_SYM(hwAccelDescr hwAccelCtx) ubyte cmac[AES_XCBC_MAC_96_RESULT_SIZE], AES_XCBC_MAC_96_Ctx * pCtx)
References MOC_SYM.
MOC_EXTERN MSTATUS AES_XCBC_PRF_128_init (MOC_SYM(hwAccelDescr hwAccelCtx) const ubyte keyMaterial[], sbyte4 keyLength, AES_XCBC_PRF_128_Ctx * pCtx)
References AES_BLOCK_SIZE, AES_XCBC_MAC_96_init(), AES_XCBC_PRF_128_final(), AES_XCBC_PRF_128_update, MOC_SYM, and MSTATUS.
MOC_EXTERN MSTATUS AES_XCBC_PRF_128_update (MOC_SYM(hwAccelDescr hwAccelCtx) const ubyte * data, sbyte4 dataLength, AES_XCBC_PRF_128_Ctx * pCtx)
MOC_EXTERN MSTATUS AES_XCBC_PRF_128_final (MOC_SYM(hwAccelDescr hwAccelCtx) ubyte cmac[AES_XCBC_PRF_128_RESULT_SIZE], AES_XCBC_PRF_128_Ctx * pCtx)
References MOC_SYM.
Referenced by AES_XCBC_PRF_128_init().