Velocite Systems Protected Point to Point Solution: aes.c File Reference
aes.c File Reference
#include "../p3kbase.h"
#include "moptions.h"
#include "mtypes.h"
#include "mocana.h"
#include "hw_accel.h"
#include "mdefs.h"
#include "merrors.h"
#include "mrtos.h"
#include "mstdlib.h"
#include "debug_console.h"
#include "aesalgo.h"
#include "aes.h"
Functions
BulkCtx CreateAESCtx (MOC_SYM(hwAccelDescr hwAccelCtx) ubyte *keyMaterial, sbyte4 keyLength, sbyte4 encrypt)
MSTATUS DeleteAESCtx (MOC_SYM(hwAccelDescr hwAccelCtx) BulkCtx ctx)
MSTATUS DoAES (MOC_SYM(hwAccelDescr hwAccelCtx) BulkCtx ctx, ubyte *data, sbyte4 dataLength, sbyte4 encrypt, ubyte *iv)
Function Documentation
BulkCtx CreateAESCtx (MOC_SYM(hwAccelDescr hwAccelCtx) ubyte * keyMaterial, sbyte4 keyLength, sbyte4 encrypt)
References AESALGO_makeAesKey(), MODE_CBC, NULL, p3free, and p3malloc.
Referenced by AESKWRAP_decrypt(), AESKWRAP_encrypt(), and p3_init_crypto().
MSTATUS DeleteAESCtx (MOC_SYM(hwAccelDescr hwAccelCtx) BulkCtx ctx)
References NULL, and p3free.
Referenced by AESKWRAP_decrypt(), AESKWRAP_encrypt(), and p3_rekey().
MSTATUS DoAES (MOC_SYM(hwAccelDescr hwAccelCtx) BulkCtx ctx, ubyte * data, sbyte4 dataLength, sbyte4 encrypt, ubyte * iv)
References AES_BLOCK_SIZE, AESALGO_blockDecrypt(), AESALGO_blockEncrypt(), DEBUG_ERROR, DEBUG_SSL_TRANSPORT, MSTATUS, p3errmsg(), and p3MSG_ERR.
Referenced by AESKWRAP_decrypt(), AESKWRAP_encrypt(), p3_decrypt(), and p3_encrypt().