Velocite Systems Protected Point to Point Solution: aes_eax.c File Reference
aes_eax.c File Reference
#include "../common/moptions.h"
#include "../common/mtypes.h"
#include "../common/mocana.h"
#include "../crypto/hw_accel.h"
#include "../common/mdefs.h"
#include "../common/merrors.h"
#include "../common/mstdlib.h"
#include "../common/mrtos.h"
#include "../crypto/aes.h"
#include "../crypto/aes_ctr.h"
#include "../crypto/aes_cmac.h"
#include "../crypto/aes_eax.h"
#include "../common/debug_console.h"
#include "../crypto/aesalgo.h"
Functions
MSTATUS AES_EAX_init (MOC_SYM(hwAccelDescr hwAccelCtx) const ubyte *keyMaterial, ubyte4 keyLength, const ubyte *nonce, ubyte4 nonceLength, AES_EAX_Ctx *pCtx)
MSTATUS AES_EAX_updateHeader (MOC_SYM(hwAccelDescr hwAccelCtx) const ubyte *headerData, sbyte4 dataLength, AES_EAX_Ctx *pCtx)
MSTATUS AES_EAX_getPlainText (MOC_SYM(hwAccelDescr hwAccelCtx) ubyte *cipherText, sbyte4 cipherLen, AES_EAX_Ctx *pCtx)
MSTATUS AES_EAX_encryptMessage (MOC_SYM(hwAccelDescr hwAccelCtx) ubyte *msgData, sbyte4 msgLen, AES_EAX_Ctx *pCtx)
MSTATUS AES_EAX_final (MOC_SYM(hwAccelDescr hwAccelCtx) ubyte tag[], sbyte4 tagLen, AES_EAX_Ctx *pCtx)
MSTATUS AES_EAX_generateTag (MOC_SYM(hwAccelDescr hwAccelCtx) const ubyte *cipherText, sbyte4 cipherLen, const ubyte *header, sbyte4 headerLen, ubyte tag[], sbyte4 tagLen, AES_EAX_Ctx *pCtx)
Function Documentation
MSTATUS AES_EAX_init (MOC_SYM(hwAccelDescr hwAccelCtx) const ubyte * keyMaterial, ubyte4 keyLength, const ubyte * nonce, ubyte4 nonceLength, AES_EAX_Ctx * pCtx)
References AES_BLOCK_SIZE, AES_OMAC_final(), AES_OMAC_update(), AESALGO_makeAesKey(), AES_EAX_Ctx::aesCTRCtx, AES_EAX_Ctx::cipherOMAC, aesCTRCipherContext::counterBlock, aesCTRCipherContext::ctx, AES_EAX_Ctx::headerOMAC, MOC_SYM, MODE_CBC, MSTATUS, AES_EAX_Ctx::N, aesCTRCipherContext::offset, and aesCTRCipherContext::u.
MSTATUS AES_EAX_updateHeader (MOC_SYM(hwAccelDescr hwAccelCtx) const ubyte * headerData, sbyte4 dataLength, AES_EAX_Ctx * pCtx)
References AES_OMAC_update(), AES_EAX_Ctx::aesCTRCtx, aesCTRCipherContext::ctx, AES_EAX_Ctx::headerOMAC, and MOC_SYM.
MSTATUS AES_EAX_getPlainText (MOC_SYM(hwAccelDescr hwAccelCtx) ubyte * cipherText, sbyte4 cipherLen, AES_EAX_Ctx * pCtx)
References AES_EAX_Ctx::aesCTRCtx, DoAESCTR(), MOC_SYM, and NULL.
MSTATUS AES_EAX_encryptMessage (MOC_SYM(hwAccelDescr hwAccelCtx) ubyte * msgData, sbyte4 msgLen, AES_EAX_Ctx * pCtx)
References AES_OMAC_update(), AES_EAX_Ctx::aesCTRCtx, AES_EAX_Ctx::cipherOMAC, aesCTRCipherContext::ctx, DoAESCTR(), MOC_SYM, MSTATUS, and NULL.
MSTATUS AES_EAX_final (MOC_SYM(hwAccelDescr hwAccelCtx) ubyte tag[], sbyte4 tagLen, AES_EAX_Ctx * pCtx)
References AES_BLOCK_SIZE, AES_OMAC_final(), AES_EAX_Ctx::aesCTRCtx, AES_EAX_Ctx::cipherOMAC, CMAC_RESULT_SIZE, aesCTRCipherContext::ctx, AES_EAX_Ctx::headerOMAC, MOC_SYM, MSTATUS, and AES_EAX_Ctx::N.
MSTATUS AES_EAX_generateTag (MOC_SYM(hwAccelDescr hwAccelCtx) const ubyte * cipherText, sbyte4 cipherLen, const ubyte * header, sbyte4 headerLen, ubyte tag[], sbyte4 tagLen, AES_EAX_Ctx * pCtx)
References AES_BLOCK_SIZE, AES_OMAC_final(), AES_OMAC_update(), AES_EAX_Ctx::aesCTRCtx, AES_EAX_Ctx::cipherOMAC, CMAC_RESULT_SIZE, aesCTRCipherContext::ctx, AES_EAX_Ctx::headerOMAC, MOC_SYM, MSTATUS, and AES_EAX_Ctx::N.