Velocite Systems Protected Point to Point Solution: aes_keywrap.h File Reference
aes_keywrap.h File Reference
Functions
MOC_EXTERN MSTATUS AESKWRAP_encrypt (MOC_SYM(hwAccelDescr hwAccelCtx) ubyte *keyMaterial, sbyte4 keyLength, const ubyte *data, ubyte4 dataLen, ubyte *retData)
MOC_EXTERN MSTATUS AESKWRAP_decrypt (MOC_SYM(hwAccelDescr hwAccelCtx) ubyte *keyMaterial, sbyte4 keyLength, const ubyte *data, ubyte4 dataLen, ubyte *retData)
Function Documentation
MOC_EXTERN MSTATUS AESKWRAP_encrypt (MOC_SYM(hwAccelDescr hwAccelCtx) ubyte * keyMaterial, sbyte4 keyLength, const ubyte * data, ubyte4 dataLen, ubyte * retData)
References CreateAESCtx(), DeleteAESCtx(), DoAES(), MOC_SYM, MSTATUS, and NULL.
MOC_EXTERN MSTATUS AESKWRAP_decrypt (MOC_SYM(hwAccelDescr hwAccelCtx) ubyte * keyMaterial, sbyte4 keyLength, const ubyte * data, ubyte4 dataLen, ubyte * retData)
References CreateAESCtx(), DeleteAESCtx(), DoAES(), MOC_SYM, MSTATUS, and NULL.