Velocite Systems Protected Point to Point Solution: aes_ecb.h File Reference
aes_ecb.h File Reference
Detailed Description
AES developer API header. This header file contains definitions, enumerations, structures, and function declarations used for AES encryption and decryption.
Since:
5.0.5
Version:
5.0.5 and later
! Flags There are no flag dependencies to enable the functions in this header file.
! External Functions This file contains the following public ($extern$) function declarations:
CreateAESECBCtx
DeleteAESECBCtx
DoAESECB
Functions
MOC_EXTERN BulkCtx CreateAESECBCtx (MOC_SYM(hwAccelDescr hwAccelCtx) ubyte *keyMaterial, sbyte4 keyLength, sbyte4 encrypt)
MOC_EXTERN MSTATUS DeleteAESECBCtx (MOC_SYM(hwAccelDescr hwAccelCtx) BulkCtx *ctx)
MOC_EXTERN MSTATUS DoAESECB (MOC_SYM(hwAccelDescr hwAccelCtx) BulkCtx ctx, ubyte *data, sbyte4 dataLength, sbyte4 encrypt, ubyte *iv)
Function Documentation
MOC_EXTERN BulkCtx CreateAESECBCtx (MOC_SYM(hwAccelDescr hwAccelCtx) ubyte * keyMaterial, sbyte4 keyLength, sbyte4 encrypt)
References AESALGO_makeAesKey(), FREE, MALLOC, MODE_ECB, and NULL.
MOC_EXTERN MSTATUS DeleteAESECBCtx (MOC_SYM(hwAccelDescr hwAccelCtx) BulkCtx * ctx)
References FREE, and NULL.
MOC_EXTERN MSTATUS DoAESECB (MOC_SYM(hwAccelDescr hwAccelCtx) BulkCtx ctx, ubyte * data, sbyte4 dataLength, sbyte4 encrypt, ubyte * iv)
References AES_BLOCK_SIZE, AESALGO_blockDecrypt(), AESALGO_blockEncrypt(), DEBUG_ERROR, DEBUG_SSL_TRANSPORT, and MSTATUS.