Velocite Systems Protected Point to Point Solution: aes_xcbc_mac_96.c File Reference
aes_xcbc_mac_96.c File Reference
#include "../common/moptions.h"
#include "../common/mtypes.h"
#include "../common/mocana.h"
#include "../crypto/hw_accel.h"
#include "../common/mdefs.h"
#include "../common/merrors.h"
#include "../crypto/aes.h"
#include "../crypto/aes_xcbc_mac_96.h"
#include "../common/mrtos.h"
#include "../common/mstdlib.h"
#include "../common/debug_console.h"
#include "../crypto/aesalgo.h"
Functions
MSTATUS AES_XCBC_MAC_96_init (MOC_SYM(hwAccelDescr hwAccelCtx) const ubyte keyMaterial[AES_BLOCK_SIZE], AES_XCBC_MAC_96_Ctx *pCtx)
MSTATUS AES_XCBC_PRF_128_init (MOC_SYM(hwAccelDescr hwAccelCtx) const ubyte keyMaterial[], sbyte4 keyLength, AES_XCBC_PRF_128_Ctx *pCtx)
MSTATUS AES_XCBC_MAC_96_update (MOC_SYM(hwAccelDescr hwAccelCtx) const ubyte *data, sbyte4 dataLength, AES_XCBC_MAC_96_Ctx *pCtx)
MSTATUS AES_XCBC_MAC_96_final (MOC_SYM(hwAccelDescr hwAccelCtx) ubyte cmac[AES_XCBC_MAC_96_RESULT_SIZE], AES_XCBC_MAC_96_Ctx *pCtx)
MSTATUS AES_XCBC_PRF_128_final (MOC_SYM(hwAccelDescr hwAccelCtx) ubyte cmac[AES_XCBC_PRF_128_RESULT_SIZE], AES_XCBC_MAC_96_Ctx *pCtx)
Function Documentation
MSTATUS AES_XCBC_MAC_96_init (MOC_SYM(hwAccelDescr hwAccelCtx) const ubyte keyMaterial[AES_BLOCK_SIZE], AES_XCBC_MAC_96_Ctx * pCtx)
References AESALGO_makeAesKey(), AES_XCBC_MAC_96_Ctx::aesCtx, AES_XCBC_MAC_96_Ctx::currBlock, AES_XCBC_MAC_96_Ctx::keyAesCtx, MODE_CBC, MSTATUS, and AES_XCBC_MAC_96_Ctx::pendingLen.
Referenced by AES_XCBC_PRF_128_init().
MSTATUS AES_XCBC_PRF_128_init (MOC_SYM(hwAccelDescr hwAccelCtx) const ubyte keyMaterial[], sbyte4 keyLength, AES_XCBC_PRF_128_Ctx * pCtx)
References AES_BLOCK_SIZE, AES_XCBC_MAC_96_init(), AES_XCBC_PRF_128_final(), AES_XCBC_PRF_128_update, MOC_SYM, and MSTATUS.
MSTATUS AES_XCBC_MAC_96_update (MOC_SYM(hwAccelDescr hwAccelCtx) const ubyte * data, sbyte4 dataLength, AES_XCBC_MAC_96_Ctx * pCtx)
References AES_BLOCK_SIZE, AES_XCBC_MAC_96_Ctx::aesCtx, aesEncrypt(), AES_XCBC_MAC_96_Ctx::currBlock, aesCipherContext::Nr, AES_XCBC_MAC_96_Ctx::pending, AES_XCBC_MAC_96_Ctx::pendingLen, and aesCipherContext::rk.
MSTATUS AES_XCBC_MAC_96_final (MOC_SYM(hwAccelDescr hwAccelCtx) ubyte cmac[AES_XCBC_MAC_96_RESULT_SIZE], AES_XCBC_MAC_96_Ctx * pCtx)
References MOC_SYM.
MSTATUS AES_XCBC_PRF_128_final (MOC_SYM(hwAccelDescr hwAccelCtx) ubyte cmac[AES_XCBC_PRF_128_RESULT_SIZE], AES_XCBC_MAC_96_Ctx * pCtx)
References MOC_SYM.
Referenced by AES_XCBC_PRF_128_init().