Velocite Systems Protected Point to Point Solution: aes.h File Reference
aes.h File Reference
Detailed Description
AES developer API header. This header file contains definitions, enumerations, structures, and function declarations used for AES encryption and decryption.
Since:
1.41
Version:
3.06 and later
! Flags No flag definitions are required to use this file.
! External Functions This file contains the following public ($extern$) function declarations:
CreateAESCtx
DeleteAESCtx
DoAES
Data Structures
struct aesCipherContext
Defines
#define AES_MAXNR 14
#define AES_BLOCK_SIZE (16)
Functions
MOC_EXTERN MSTATUS AESALGO_makeAesKey (aesCipherContext *pAesContext, sbyte4 keyLen, const ubyte *keyMaterial, sbyte4 encrypt, sbyte4 mode)
MOC_EXTERN MSTATUS AESALGO_blockEncrypt (aesCipherContext *pAesContext, ubyte *iv, ubyte *input, sbyte4 inputLen, ubyte *outBuffer, sbyte4 *pRetLength)
MOC_EXTERN MSTATUS AESALGO_blockDecrypt (aesCipherContext *pAesContext, ubyte *iv, ubyte *input, sbyte4 inputLen, ubyte *outBuffer, sbyte4 *pRetLength)
MOC_EXTERN BulkCtx CreateAESCtx (MOC_SYM(hwAccelDescr hwAccelCtx) ubyte *keyMaterial, sbyte4 keyLength, sbyte4 encrypt)
MOC_EXTERN MSTATUS DeleteAESCtx (MOC_SYM(hwAccelDescr hwAccelCtx) BulkCtx ctx)
MOC_EXTERN MSTATUS DoAES (MOC_SYM(hwAccelDescr hwAccelCtx) BulkCtx ctx, ubyte *data, sbyte4 dataLength, sbyte4 encrypt, ubyte *iv)
Define Documentation
#define AES_MAXNR 14
#define AES_BLOCK_SIZE (16)
Referenced by AES_EAX_final(), AES_EAX_generateTag(), AES_EAX_init(), AES_XCBC_MAC_96_update(), AES_XCBC_PRF_128_init(), AESALGO_blockDecrypt(), AESALGO_blockEncrypt(), CreateAESCTRCtx(), DoAES(), DoAESCTR(), DoAESCTREx(), and DoAESECB().
Function Documentation
MOC_EXTERN MSTATUS AESALGO_makeAesKey (aesCipherContext * pAesContext, sbyte4 keyLen, const ubyte * keyMaterial, sbyte4 encrypt, sbyte4 mode)
References aesKeySetupDec(), aesKeySetupEnc(), aesCipherContext::ek, aesCipherContext::encrypt, aesCipherContext::keyLen, aesCipherContext::mode, MSTATUS, aesCipherContext::Nr, NULL, p3errmsg(), p3MSG_ERR, and aesCipherContext::rk.
Referenced by AES_EAX_init(), AES_XCBC_MAC_96_init(), AESCCM_decrypt(), AESCCM_encrypt(), AESCMAC_init(), AESCTRInit(), CreateAESCtx(), and CreateAESECBCtx().
MOC_EXTERN MSTATUS AESALGO_blockEncrypt (aesCipherContext * pAesContext, ubyte * iv, ubyte * input, sbyte4 inputLen, ubyte * outBuffer, sbyte4 * pRetLength)
References AES_BLOCK_SIZE, aesEncrypt(), aesCipherContext::ek, aesCipherContext::encrypt, FALSE, aesCipherContext::mode, MODE_CBC, MODE_CFB1, MODE_ECB, MSTATUS, aesCipherContext::Nr, NULL, p3errmsg(), p3MSG_ERR, and aesCipherContext::rk.
Referenced by DoAES(), and DoAESECB().
MOC_EXTERN MSTATUS AESALGO_blockDecrypt (aesCipherContext * pAesContext, ubyte * iv, ubyte * input, sbyte4 inputLen, ubyte * outBuffer, sbyte4 * pRetLength)
References AES_BLOCK_SIZE, aesDecrypt(), aesEncrypt(), aesCipherContext::ek, aesCipherContext::encrypt, aesCipherContext::mode, MODE_CBC, MODE_CFB1, MODE_ECB, MSTATUS, aesCipherContext::Nr, NULL, p3errmsg(), p3MSG_ERR, and aesCipherContext::rk.
Referenced by DoAES(), and DoAESECB().
MOC_EXTERN BulkCtx CreateAESCtx (MOC_SYM(hwAccelDescr hwAccelCtx) ubyte * keyMaterial, sbyte4 keyLength, sbyte4 encrypt)
References AESALGO_makeAesKey(), MODE_CBC, NULL, p3free, and p3malloc.
Referenced by AESKWRAP_decrypt(), AESKWRAP_encrypt(), and p3_init_crypto().
MOC_EXTERN MSTATUS DeleteAESCtx (MOC_SYM(hwAccelDescr hwAccelCtx) BulkCtx ctx)
References NULL, and p3free.
Referenced by AESKWRAP_decrypt(), AESKWRAP_encrypt(), and p3_rekey().
MOC_EXTERN MSTATUS DoAES (MOC_SYM(hwAccelDescr hwAccelCtx) BulkCtx ctx, ubyte * data, sbyte4 dataLength, sbyte4 encrypt, ubyte * iv)
References AES_BLOCK_SIZE, AESALGO_blockDecrypt(), AESALGO_blockEncrypt(), DEBUG_ERROR, DEBUG_SSL_TRANSPORT, MSTATUS, p3errmsg(), and p3MSG_ERR.
Referenced by AESKWRAP_decrypt(), AESKWRAP_encrypt(), p3_decrypt(), and p3_encrypt().