Velocite Systems Protected Point to Point Solution: aes_cmac.c File Reference
aes_cmac.c File Reference
#include "../common/moptions.h"
#include "../common/mtypes.h"
#include "../common/mocana.h"
#include "../crypto/hw_accel.h"
#include "../common/merrors.h"
#include "../crypto/aes.h"
#include "../crypto/aes_cmac.h"
#include "../common/mdefs.h"
#include "../common/mrtos.h"
#include "../common/mstdlib.h"
#include "../common/debug_console.h"
#include "../crypto/aesalgo.h"
Functions
MSTATUS AESCMAC_init (MOC_SYM(hwAccelDescr hwAccelCtx) const ubyte *keyMaterial, sbyte4 keyLength, AESCMAC_Ctx *pCtx)
MSTATUS AESCMAC_update (MOC_SYM(hwAccelDescr hwAccelCtx) const ubyte *data, sbyte4 dataLength, AESCMAC_Ctx *pCtx)
MSTATUS AESCMAC_final (MOC_SYM(hwAccelDescr hwAccelCtx) ubyte cmac[CMAC_RESULT_SIZE], AESCMAC_Ctx *pCtx)
MSTATUS AES_OMAC_init (AES_OMAC_Ctx *pOMACCtx)
MSTATUS AES_OMAC_update (MOC_SYM(hwAccelDescr hwAccelCtx) aesCipherContext *pAESCtx, AES_OMAC_Ctx *pOMACCtx, const ubyte *data, sbyte4 dataLength)
MSTATUS AES_OMAC_final (MOC_SYM(hwAccelDescr hwAccelCtx) aesCipherContext *pAESCtx, AES_OMAC_Ctx *pOMACCtx, ubyte cmac[CMAC_RESULT_SIZE])
Function Documentation
MSTATUS AESCMAC_init (MOC_SYM(hwAccelDescr hwAccelCtx) const ubyte * keyMaterial, sbyte4 keyLength, AESCMAC_Ctx * pCtx)
References AES_OMAC_init(), AESALGO_makeAesKey(), AESCMAC_Ctx::aesCtx, MODE_CBC, MSTATUS, and AESCMAC_Ctx::omacCtx.
MSTATUS AESCMAC_update (MOC_SYM(hwAccelDescr hwAccelCtx) const ubyte * data, sbyte4 dataLength, AESCMAC_Ctx * pCtx)
References AES_OMAC_update(), AESCMAC_Ctx::aesCtx, MOC_SYM, and AESCMAC_Ctx::omacCtx.
MSTATUS AESCMAC_final (MOC_SYM(hwAccelDescr hwAccelCtx) ubyte cmac[CMAC_RESULT_SIZE], AESCMAC_Ctx * pCtx)
References AES_OMAC_final(), AESCMAC_Ctx::aesCtx, MOC_SYM, and AESCMAC_Ctx::omacCtx.
MSTATUS AES_OMAC_init (AES_OMAC_Ctx * pOMACCtx)
References AES_OMAC_Ctx::currBlock, and AES_OMAC_Ctx::pendingLen.
Referenced by AESCMAC_init().
MSTATUS AES_OMAC_update (MOC_SYM(hwAccelDescr hwAccelCtx) aesCipherContext * pAESCtx, AES_OMAC_Ctx * pOMACCtx, const ubyte * data, sbyte4 dataLength)
References aesEncrypt(), AES_OMAC_Ctx::currBlock, AES_OMAC_Ctx::pending, and AES_OMAC_Ctx::pendingLen.
Referenced by AES_EAX_encryptMessage(), AES_EAX_generateTag(), AES_EAX_init(), AES_EAX_updateHeader(), and AESCMAC_update().
MSTATUS AES_OMAC_final (MOC_SYM(hwAccelDescr hwAccelCtx) aesCipherContext * pAESCtx, AES_OMAC_Ctx * pOMACCtx, ubyte cmac[CMAC_RESULT_SIZE])
References aesEncrypt(), AES_OMAC_Ctx::currBlock, AES_OMAC_Ctx::pending, and AES_OMAC_Ctx::pendingLen.
Referenced by AES_EAX_final(), AES_EAX_generateTag(), AES_EAX_init(), and AESCMAC_final().