Velocite Systems Protected Point to Point Solution: aes_ctr.c File Reference
aes_ctr.c File Reference
#include "../common/moptions.h"
#include "../common/mtypes.h"
#include "../common/mocana.h"
#include "../crypto/hw_accel.h"
#include "../common/mdefs.h"
#include "../common/merrors.h"
#include "../crypto/aes.h"
#include "../crypto/aes_ctr.h"
#include "../common/mrtos.h"
#include "../common/mstdlib.h"
#include "../common/debug_console.h"
#include "../crypto/aesalgo.h"
Functions
MSTATUS AESCTRInit (MOC_SYM(hwAccelDescr hwAccelCtx) AES_CTR_Ctx *ctx, const ubyte *keyMaterial, sbyte4 keyLength, const ubyte initCounter[AES_BLOCK_SIZE])
BulkCtx CreateAESCTRCtx (MOC_SYM(hwAccelDescr hwAccelCtx) const ubyte *keyMaterial, sbyte4 keyLength, sbyte4 encrypt)
MSTATUS DeleteAESCTRCtx (MOC_SYM(hwAccelDescr hwAccelCtx) BulkCtx *ctx)
MSTATUS DoAESCTREx (MOC_SYM(hwAccelDescr hwAccelCtx) BulkCtx ctx, ubyte *data, sbyte4 dataLength, sbyte4 encrypt, ubyte *iv, sbyte4 limit)
MSTATUS DoAESCTR (MOC_SYM(hwAccelDescr hwAccelCtx) BulkCtx ctx, ubyte *data, sbyte4 dataLength, sbyte4 encrypt, ubyte *iv)
Function Documentation
MSTATUS AESCTRInit (MOC_SYM(hwAccelDescr hwAccelCtx) AES_CTR_Ctx * ctx, const ubyte * keyMaterial, sbyte4 keyLength, const ubyte initCounter[AES_BLOCK_SIZE])
References AESALGO_makeAesKey(), and MODE_ECB.
Referenced by CreateAESCTRCtx().
BulkCtx CreateAESCTRCtx (MOC_SYM(hwAccelDescr hwAccelCtx) const ubyte * keyMaterial, sbyte4 keyLength, sbyte4 encrypt)
References AES_BLOCK_SIZE, AESCTRInit(), FREE, MALLOC, MOC_SYM, MOC_UNUSED, and NULL.
MSTATUS DeleteAESCTRCtx (MOC_SYM(hwAccelDescr hwAccelCtx) BulkCtx * ctx)
References FREE, and NULL.
MSTATUS DoAESCTREx (MOC_SYM(hwAccelDescr hwAccelCtx) BulkCtx ctx, ubyte * data, sbyte4 dataLength, sbyte4 encrypt, ubyte * iv, sbyte4 limit)
References AES_BLOCK_SIZE, aesCTRCipherContext::counterBlock, aesCTRCipherContext::encBlock, MOC_UNUSED, aesCTRCipherContext::offset, and aesCTRCipherContext::u.
Referenced by DoAESCTR().
MSTATUS DoAESCTR (MOC_SYM(hwAccelDescr hwAccelCtx) BulkCtx ctx, ubyte * data, sbyte4 dataLength, sbyte4 encrypt, ubyte * iv)
References AES_BLOCK_SIZE, DoAESCTREx(), and MOC_SYM.
Referenced by AES_EAX_encryptMessage(), and AES_EAX_getPlainText().