Velocite Systems Protected Point to Point Solution: aes_eax.h File Reference
aes_eax.h File Reference
Data Structures
struct AES_EAX_Ctx
Defines
#define AES_EAX_decryptMessage AES_EAX_encryptMessage
Functions
MOC_EXTERN MSTATUS AES_EAX_init (MOC_SYM(hwAccelDescr hwAccelCtx) const ubyte *keyMaterial, ubyte4 keyLength, const ubyte *nonce, ubyte4 nonceLength, AES_EAX_Ctx *pCtx)
MOC_EXTERN MSTATUS AES_EAX_updateHeader (MOC_SYM(hwAccelDescr hwAccelCtx) const ubyte *headerData, sbyte4 dataLength, AES_EAX_Ctx *pCtx)
MOC_EXTERN MSTATUS AES_EAX_encryptMessage (MOC_SYM(hwAccelDescr hwAccelCtx) ubyte *msgData, sbyte4 msgLen, AES_EAX_Ctx *pCtx)
MOC_EXTERN MSTATUS AES_EAX_final (MOC_SYM(hwAccelDescr hwAccelCtx) ubyte tag[], sbyte4 tagLen, AES_EAX_Ctx *pCtx)
MOC_EXTERN MSTATUS AES_EAX_generateTag (MOC_SYM(hwAccelDescr hwAccelCtx) const ubyte *cipherText, sbyte4 cipherLen, const ubyte *header, sbyte4 headerLen, ubyte tag[], sbyte4 tagLen, AES_EAX_Ctx *pCtx)
MOC_EXTERN MSTATUS AES_EAX_getPlainText (MOC_SYM(hwAccelDescr hwAccelCtx) ubyte *cipherText, sbyte4 cipherLen, AES_EAX_Ctx *pCtx)
Define Documentation
#define AES_EAX_decryptMessage AES_EAX_encryptMessage
Function Documentation
MOC_EXTERN MSTATUS AES_EAX_init (MOC_SYM(hwAccelDescr hwAccelCtx) const ubyte * keyMaterial, ubyte4 keyLength, const ubyte * nonce, ubyte4 nonceLength, AES_EAX_Ctx * pCtx)
References AES_BLOCK_SIZE, AES_OMAC_final(), AES_OMAC_update(), AESALGO_makeAesKey(), AES_EAX_Ctx::aesCTRCtx, AES_EAX_Ctx::cipherOMAC, aesCTRCipherContext::counterBlock, aesCTRCipherContext::ctx, AES_EAX_Ctx::headerOMAC, MOC_SYM, MODE_CBC, MSTATUS, AES_EAX_Ctx::N, aesCTRCipherContext::offset, and aesCTRCipherContext::u.
MOC_EXTERN MSTATUS AES_EAX_updateHeader (MOC_SYM(hwAccelDescr hwAccelCtx) const ubyte * headerData, sbyte4 dataLength, AES_EAX_Ctx * pCtx)
References AES_OMAC_update(), AES_EAX_Ctx::aesCTRCtx, aesCTRCipherContext::ctx, AES_EAX_Ctx::headerOMAC, and MOC_SYM.
MOC_EXTERN MSTATUS AES_EAX_encryptMessage (MOC_SYM(hwAccelDescr hwAccelCtx) ubyte * msgData, sbyte4 msgLen, AES_EAX_Ctx * pCtx)
References AES_OMAC_update(), AES_EAX_Ctx::aesCTRCtx, AES_EAX_Ctx::cipherOMAC, aesCTRCipherContext::ctx, DoAESCTR(), MOC_SYM, MSTATUS, and NULL.
MOC_EXTERN MSTATUS AES_EAX_final (MOC_SYM(hwAccelDescr hwAccelCtx) ubyte tag[], sbyte4 tagLen, AES_EAX_Ctx * pCtx)
References AES_BLOCK_SIZE, AES_OMAC_final(), AES_EAX_Ctx::aesCTRCtx, AES_EAX_Ctx::cipherOMAC, CMAC_RESULT_SIZE, aesCTRCipherContext::ctx, AES_EAX_Ctx::headerOMAC, MOC_SYM, MSTATUS, and AES_EAX_Ctx::N.
MOC_EXTERN MSTATUS AES_EAX_generateTag (MOC_SYM(hwAccelDescr hwAccelCtx) const ubyte * cipherText, sbyte4 cipherLen, const ubyte * header, sbyte4 headerLen, ubyte tag[], sbyte4 tagLen, AES_EAX_Ctx * pCtx)
References AES_BLOCK_SIZE, AES_OMAC_final(), AES_OMAC_update(), AES_EAX_Ctx::aesCTRCtx, AES_EAX_Ctx::cipherOMAC, CMAC_RESULT_SIZE, aesCTRCipherContext::ctx, AES_EAX_Ctx::headerOMAC, MOC_SYM, MSTATUS, and AES_EAX_Ctx::N.
MOC_EXTERN MSTATUS AES_EAX_getPlainText (MOC_SYM(hwAccelDescr hwAccelCtx) ubyte * cipherText, sbyte4 cipherLen, AES_EAX_Ctx * pCtx)
References AES_EAX_Ctx::aesCTRCtx, DoAESCTR(), MOC_SYM, and NULL.