Velocite Systems Protected Point to Point Solution: aes_ctr.h File Reference
aes_ctr.h File Reference
Detailed Description
AES developer API header. This header file contains definitions, enumerations, structures, and function declarations used for AES encryption and decryption.
Since:
3.0.6
Version:
5.0.5 and later
! Flags There are no flag dependencies to enable the functions in this header file.
! External Functions This file contains the following public ($extern$) function declarations:
CreateAESCTRCtx
DeleteAESCTRCtx
DoAESCTR
Data Structures
struct aesCTRCipherContext
Typedefs
typedef struct aesCTRCipherContext AES_CTR_Ctx
Functions
MOC_EXTERN BulkCtx CreateAESCTRCtx (MOC_SYM(hwAccelDescr hwAccelCtx) const ubyte *keyMaterial, sbyte4 keyLength, sbyte4 encrypt)
MOC_EXTERN MSTATUS DeleteAESCTRCtx (MOC_SYM(hwAccelDescr hwAccelCtx) BulkCtx *ctx)
MOC_EXTERN MSTATUS DoAESCTR (MOC_SYM(hwAccelDescr hwAccelCtx) BulkCtx ctx, ubyte *data, sbyte4 dataLength, sbyte4 encrypt, ubyte *iv)
MOC_EXTERN MSTATUS AESCTRInit (MOC_SYM(hwAccelDescr hwAccelCtx) AES_CTR_Ctx *aesCtrCtx, const ubyte *keyMaterial, sbyte4 keyLength, const ubyte initCounter[AES_BLOCK_SIZE])
MOC_EXTERN MSTATUS DoAESCTREx (MOC_SYM(hwAccelDescr hwAccelCtx) BulkCtx ctx, ubyte *data, sbyte4 dataLength, sbyte4 encrypt, ubyte *iv, sbyte4 limit)
Typedef Documentation
typedef struct aesCTRCipherContext AES_CTR_Ctx
Function Documentation
MOC_EXTERN BulkCtx CreateAESCTRCtx (MOC_SYM(hwAccelDescr hwAccelCtx) const ubyte * keyMaterial, sbyte4 keyLength, sbyte4 encrypt)
References AES_BLOCK_SIZE, AESCTRInit(), FREE, MALLOC, MOC_SYM, MOC_UNUSED, and NULL.
MOC_EXTERN MSTATUS DeleteAESCTRCtx (MOC_SYM(hwAccelDescr hwAccelCtx) BulkCtx * ctx)
References FREE, and NULL.
MOC_EXTERN MSTATUS DoAESCTR (MOC_SYM(hwAccelDescr hwAccelCtx) BulkCtx ctx, ubyte * data, sbyte4 dataLength, sbyte4 encrypt, ubyte * iv)
References AES_BLOCK_SIZE, DoAESCTREx(), and MOC_SYM.
Referenced by AES_EAX_encryptMessage(), and AES_EAX_getPlainText().
MOC_EXTERN MSTATUS AESCTRInit (MOC_SYM(hwAccelDescr hwAccelCtx) AES_CTR_Ctx * aesCtrCtx, const ubyte * keyMaterial, sbyte4 keyLength, const ubyte initCounter[AES_BLOCK_SIZE])
References AESALGO_makeAesKey(), and MODE_ECB.
Referenced by CreateAESCTRCtx().
MOC_EXTERN MSTATUS DoAESCTREx (MOC_SYM(hwAccelDescr hwAccelCtx) BulkCtx ctx, ubyte * data, sbyte4 dataLength, sbyte4 encrypt, ubyte * iv, sbyte4 limit)
References AES_BLOCK_SIZE, aesCTRCipherContext::counterBlock, aesCTRCipherContext::encBlock, MOC_UNUSED, aesCTRCipherContext::offset, and aesCTRCipherContext::u.
Referenced by DoAESCTR().