Velocite Systems Protected Point to Point Solution: aes_keywrap.c File Reference
aes_keywrap.c File Reference
#include "../common/moptions.h"
#include "../common/mtypes.h"
#include "../common/mocana.h"
#include "../crypto/hw_accel.h"
#include "../common/mdefs.h"
#include "../common/merrors.h"
#include "../common/mrtos.h"
#include "../common/mstdlib.h"
#include "../common/debug_console.h"
#include "../crypto/aesalgo.h"
#include "../crypto/aes.h"
#include "../crypto/aes_keywrap.h"
Functions
MSTATUS AESKWRAP_encrypt (MOC_SYM(hwAccelDescr hwAccelCtx) ubyte *keyMaterial, sbyte4 keyLength, const ubyte *data, ubyte4 dataLen, ubyte *retData)
MSTATUS AESKWRAP_decrypt (MOC_SYM(hwAccelDescr hwAccelCtx) ubyte *keyMaterial, sbyte4 keyLength, const ubyte *data, ubyte4 dataLen, ubyte *retData)
Function Documentation
MSTATUS AESKWRAP_encrypt (MOC_SYM(hwAccelDescr hwAccelCtx) ubyte * keyMaterial, sbyte4 keyLength, const ubyte * data, ubyte4 dataLen, ubyte * retData)
References CreateAESCtx(), DeleteAESCtx(), DoAES(), MOC_SYM, MSTATUS, and NULL.
MSTATUS AESKWRAP_decrypt (MOC_SYM(hwAccelDescr hwAccelCtx) ubyte * keyMaterial, sbyte4 keyLength, const ubyte * data, ubyte4 dataLen, ubyte * retData)
References CreateAESCtx(), DeleteAESCtx(), DoAES(), MOC_SYM, MSTATUS, and NULL.