Velocite Systems Protected Point to Point Solution: aesalgo.c File Reference
aesalgo.c File Reference
#include "../p3kbase.h"
#include "moptions.h"
#include "mtypes.h"
#include "mocana.h"
#include "hw_accel.h"
#include "mdefs.h"
#include "merrors.h"
#include "mrtos.h"
#include "mstdlib.h"
#include "aesalgo.h"
#include "aes.h"
Defines
#define GETU32(pt) (((ubyte4)(pt)[0] << 24) ^ ((ubyte4)(pt)[1] << 16) ^ ((ubyte4)(pt)[2] << 8) ^ ((ubyte4)(pt)[3]))
#define PUTU32(ct, st) { (ct)[0] = (ubyte)((st) >> 24); (ct)[1] = (ubyte)((st) >> 16); (ct)[2] = (ubyte)((st) >> 8); (ct)[3] = (ubyte)(st); }
Functions
sbyte4 aesKeySetupEnc (ubyte4 rk[], const ubyte cipherKey[], sbyte4 keyBits)
sbyte4 aesKeySetupDec (ubyte4 rk[], const ubyte cipherKey[], sbyte4 keyBits)
void aesEncrypt (ubyte4 rk[], sbyte4 Nr, ubyte pt[16], ubyte ct[16])
void aesDecrypt (ubyte4 rk[], sbyte4 Nr, ubyte ct[16], ubyte pt[16])
MSTATUS AESALGO_makeAesKey (aesCipherContext *pAesContext, sbyte4 keyLen, const ubyte *keyMaterial, sbyte4 encrypt, sbyte4 mode)
MSTATUS AESALGO_blockEncrypt (aesCipherContext *pAesContext, ubyte *iv, ubyte *input, sbyte4 inputLen, ubyte *outBuffer, sbyte4 *pRetLength)
MSTATUS AESALGO_blockDecrypt (aesCipherContext *pAesContext, ubyte *iv, ubyte *input, sbyte4 inputLen, ubyte *outBuffer, sbyte4 *pRetLength)
Define Documentation
#define GETU32 (pt) (((ubyte4)(pt)[0] << 24) ^ ((ubyte4)(pt)[1] << 16) ^ ((ubyte4)(pt)[2] << 8) ^ ((ubyte4)(pt)[3]))
Referenced by aesDecrypt(), aesEncrypt(), and aesKeySetupEnc().
#define PUTU32 (ct, st) { (ct)[0] = (ubyte)((st) >> 24); (ct)[1] = (ubyte)((st) >> 16); (ct)[2] = (ubyte)((st) >> 8); (ct)[3] = (ubyte)(st); }
Referenced by aesDecrypt(), and aesEncrypt().
Function Documentation
sbyte4 aesKeySetupEnc (ubyte4 rk[], const ubyte cipherKey[], sbyte4 keyBits)
Expand the cipher key into the encryption key schedule.
Returns:
the number of rounds for the given cipher key size.
References GETU32, and NULL.
Referenced by AESALGO_makeAesKey(), and aesKeySetupDec().
sbyte4 aesKeySetupDec (ubyte4 rk[], const ubyte cipherKey[], sbyte4 keyBits)
Expand the cipher key into the decryption key schedule.
Returns:
the number of rounds for the given cipher key size.
References aesKeySetupEnc(), and NULL.
Referenced by AESALGO_makeAesKey().
void aesEncrypt (ubyte4 rk[], sbyte4 Nr, ubyte pt[16], ubyte ct[16])
References GETU32, and PUTU32.
Referenced by AES_OMAC_final(), AES_OMAC_update(), AES_XCBC_MAC_96_update(), AESALGO_blockDecrypt(), and AESALGO_blockEncrypt().
void aesDecrypt (ubyte4 rk[], sbyte4 Nr, ubyte ct[16], ubyte pt[16])
References GETU32, and PUTU32.
Referenced by AESALGO_blockDecrypt().
MSTATUS AESALGO_makeAesKey (aesCipherContext * pAesContext, sbyte4 keyLen, const ubyte * keyMaterial, sbyte4 encrypt, sbyte4 mode)
References aesKeySetupDec(), aesKeySetupEnc(), aesCipherContext::ek, aesCipherContext::encrypt, aesCipherContext::keyLen, aesCipherContext::mode, MSTATUS, aesCipherContext::Nr, NULL, p3errmsg(), p3MSG_ERR, and aesCipherContext::rk.
Referenced by AES_EAX_init(), AES_XCBC_MAC_96_init(), AESCCM_decrypt(), AESCCM_encrypt(), AESCMAC_init(), AESCTRInit(), CreateAESCtx(), and CreateAESECBCtx().
MSTATUS AESALGO_blockEncrypt (aesCipherContext * pAesContext, ubyte * iv, ubyte * input, sbyte4 inputLen, ubyte * outBuffer, sbyte4 * pRetLength)
References AES_BLOCK_SIZE, aesEncrypt(), aesCipherContext::ek, aesCipherContext::encrypt, FALSE, aesCipherContext::mode, MODE_CBC, MODE_CFB1, MODE_ECB, MSTATUS, aesCipherContext::Nr, NULL, p3errmsg(), p3MSG_ERR, and aesCipherContext::rk.
Referenced by DoAES(), and DoAESECB().
MSTATUS AESALGO_blockDecrypt (aesCipherContext * pAesContext, ubyte * iv, ubyte * input, sbyte4 inputLen, ubyte * outBuffer, sbyte4 * pRetLength)
References AES_BLOCK_SIZE, aesDecrypt(), aesEncrypt(), aesCipherContext::ek, aesCipherContext::encrypt, aesCipherContext::mode, MODE_CBC, MODE_CFB1, MODE_ECB, MSTATUS, aesCipherContext::Nr, NULL, p3errmsg(), p3MSG_ERR, and aesCipherContext::rk.
Referenced by DoAES(), and DoAESECB().