Velocite Systems Protected Point to Point Solution: aesalgo.h File Reference
aesalgo.h File Reference
Defines
#define MODE_ECB 1
#define MODE_CBC 2
#define MODE_CFB1 3
Functions
MOC_EXTERN sbyte4 aesKeySetupEnc (ubyte4 rk[], const ubyte cipherKey[], sbyte4 keyBits)
MOC_EXTERN sbyte4 aesKeySetupDec (ubyte4 rk[], const ubyte cipherKey[], sbyte4 keyBits)
MOC_EXTERN void aesEncrypt (ubyte4 rk[], sbyte4 Nr, ubyte pt[16], ubyte ct[16])
MOC_EXTERN void aesDecrypt (ubyte4 rk[], sbyte4 Nr, ubyte ct[16], ubyte pt[16])
Define Documentation
#define MODE_ECB 1
Referenced by AESALGO_blockDecrypt(), AESALGO_blockEncrypt(), AESCCM_decrypt(), AESCCM_encrypt(), AESCTRInit(), and CreateAESECBCtx().
#define MODE_CBC 2
Referenced by AES_EAX_init(), AES_XCBC_MAC_96_init(), AESALGO_blockDecrypt(), AESALGO_blockEncrypt(), AESCMAC_init(), and CreateAESCtx().
#define MODE_CFB1 3
Referenced by AESALGO_blockDecrypt(), and AESALGO_blockEncrypt().
Function Documentation
MOC_EXTERN sbyte4 aesKeySetupEnc (ubyte4 rk[], const ubyte cipherKey[], sbyte4 keyBits)
Expand the cipher key into the encryption key schedule.
Returns:
the number of rounds for the given cipher key size.
References GETU32, and NULL.
Referenced by AESALGO_makeAesKey(), and aesKeySetupDec().
MOC_EXTERN sbyte4 aesKeySetupDec (ubyte4 rk[], const ubyte cipherKey[], sbyte4 keyBits)
Expand the cipher key into the decryption key schedule.
Returns:
the number of rounds for the given cipher key size.
References aesKeySetupEnc(), and NULL.
Referenced by AESALGO_makeAesKey().
MOC_EXTERN void aesEncrypt (ubyte4 rk[], sbyte4 Nr, ubyte pt[16], ubyte ct[16])
References GETU32, and PUTU32.
Referenced by AES_OMAC_final(), AES_OMAC_update(), AES_XCBC_MAC_96_update(), AESALGO_blockDecrypt(), and AESALGO_blockEncrypt().
MOC_EXTERN void aesDecrypt (ubyte4 rk[], sbyte4 Nr, ubyte ct[16], ubyte pt[16])
References GETU32, and PUTU32.
Referenced by AESALGO_blockDecrypt().