Velocite Systems Protected Point to Point Solution: p3admin.c File Reference
p3admin.c File Reference
Detailed Description
Protected Point to Point adminstrator interface file
Copyright (C) Velocite 2010
The adminstrator interface is used to manage the key server as well as secondary P3 systems.
#include "p3admin.h"
#include "p3pri_ui.h"
#include "p3sec_ui.h"
Defines
#define _p3ADMIN_C
Functions
int main (int argc, char *argv[])
int init_admin ()
int admin_handler ()
Variables
p3admin * admin
char tbuf [4092]
char * admbuf = tbuf
Define Documentation
#define _p3ADMIN_C
Function Documentation
int main (int argc, char * argv[])
Function:
main
Description:
Initialize the P3 administration application.
Inputs:
argc: Number of arguments
argv: Argument vector
Outputs:
int: Status
0 = OK
<0 = Error
References admin_handler(), init_admin(), MSG_TIME, NULL, p3buf, p3calloc, p3errmsg(), and p3MSG_CRIT.
int init_admin ()
Function:
init_admin
Description:
Initialize the adminstrator interface.
Inputs:
None
Outputs:
int: Status
0 = OK
<0 = Error
Referenced by main().
int admin_handler ()
Function:
admin_handler
Description:
Handle input from the adminstrator interface.
Inputs:
None
Outputs:
int: Status
0 = OK
<0 = Error
Referenced by main().
Variable Documentation
p3admin* admin
Global variable usage
char tbuf[4092]
Working buffer
char * admbuf = tbuf