Velocite Systems Protected Point to Point Solution: p3kcrypto.h File Reference
p3kcrypto.h File Reference
Detailed Description
Protected Point to Point key server header file
Copyright (C) Velocite 2010
#include "p3linux.h"
Data Structures
struct _p3key_serv
struct _p3key_mgr
struct _p3key
struct _p3keymgmt
Defines
#define p3KTYPE_AES128 1
#define p3KSIZE_AES128 16
#define p3KTYPE_AES256 2
#define p3KSIZE_AES256 32
#define p3MAX_KSIZE p3KSIZE_AES256
#define p3CRYPTO_ALIGN 16
#define p3DATENC1 1
#define p3DATDEC1 2
#define p3DATENC0 3
#define p3DATDEC0 4
#define p3CTLENC1 5
#define p3CTLDEC1 6
#define p3CTLENC0 7
#define p3CTLDEC0 8
#define p3KMG_KEYS 2
Typedefs
typedef struct _p3key_serv p3key_serv
typedef struct _p3key_mgr p3key_mgr
typedef struct _p3key p3key
typedef struct _p3keymgmt p3keymgmt
Functions
int p3_get_key_size (int type)
int p3_get_key (p3key *key, p3key_mgr *key_mgr)
p3key ** p3_get_key_array (int size, int number, p3key_mgr *key_mgr)
int p3_init_crypto (p3keymgmt *keys)
int p3_rekey (p3keymgmt *keys)
int p3_encrypt (unsigned char *buffer, int size, unsigned int id, int key, p3keymgmt *keys)
int p3_decrypt (unsigned char *buffer, int size, unsigned int id, int key, p3keymgmt *keys)
Define Documentation
#define p3KTYPE_AES128 1
#define p3KSIZE_AES128 16
#define p3KTYPE_AES256 2
#define p3KSIZE_AES256 32
#define p3MAX_KSIZE p3KSIZE_AES256
#define p3CRYPTO_ALIGN 16
Referenced by packet_handler().
#define p3DATENC1 1
Referenced by p3_encrypt(), p3send_control(), and packet_handler().
#define p3DATDEC1 2
Referenced by p3_decrypt(), and packet_handler().
#define p3DATENC0 3
Referenced by p3_encrypt().
#define p3DATDEC0 4
Referenced by p3_decrypt(), and packet_handler().
#define p3CTLENC1 5
Referenced by p3_encrypt(), and p3send_control().
#define p3CTLDEC1 6
Referenced by p3_decrypt(), and packet_handler().
#define p3CTLENC0 7
Referenced by p3_encrypt().
#define p3CTLDEC0 8
Referenced by p3_decrypt(), and packet_handler().
#define p3KMG_KEYS 2
Typedef Documentation
typedef struct _p3key_serv p3key_serv
typedef struct _p3key_mgr p3key_mgr
typedef struct _p3key p3key
typedef struct _p3keymgmt p3keymgmt
Function Documentation
int p3_get_key_size (int type)
Function:
p3_get_key_size
Description:
Get the size of an encryption key.
Inputs:
type: The type of the encryption algorithm.
Outputs:
int:
0: Key size
<0: Error
References p3KSIZE_AES128, p3KSIZE_AES256, p3KTYPE_AES128, and p3KTYPE_AES256.
Referenced by parse_p3data().
int p3_get_key (p3key * key, p3key_mgr * key_mgr)
Function:
p3_get_key
Description:
Get an encryption key from the Ramdisk buffer.
Inputs:
key: The P3 key structure. The flag in the structure contains information about the key, such as its type (size). The new key is returned in this structure.
key_mgr: The P3 key manager structure that maintains information about the circular buffer of keys.
Outputs:
int: Status
0: OK
<0: Error
>0: Key unavailable, try later
References _p3key_serv::cbuf_sz, _p3key_serv::head, _p3key::key, _p3key_mgr::key_serv, key_serv, _p3key_mgr::lock, NULL, p3buf, p3errmsg(), p3lock, p3MSG_DEBUG, p3MSG_ERR, p3unlock, _p3key::size, and _p3key_serv::tail.
p3key** p3_get_key_array (int size, int number, p3key_mgr * key_mgr)
Function:
p3_get_key_array
Description:
Get an array of encryption keys. All keys in the array are true random numbers.
Inputs:
size: The size, in bytes, of the key to be retrieved
number: The number of keys in the array
key_mgr: The P3 key server structure that maintains information about the circular buffer of keys.
Outputs:
p3key**: The array containing the keys. If there is an error, NULL is returned.
References NULL.
int p3_init_crypto (p3keymgmt * keys)
Function:
p3_init_crypto
Description:
Initialize the keys for a session by creating the crypto context for each key.
The value of the data and control new key fields will be used for initializing the contexts.
Inputs:
keys: The session key managment structure.
Outputs:
int: Status
0: OK
<0: Error
References _p3keymgmt::cnewkey, CreateAESCtx(), crypto_lock, _p3keymgmt::ctldec1, _p3keymgmt::ctlenc1, _p3keymgmt::datdec1, _p3keymgmt::datenc1, _p3keymgmt::dnewkey, FALSE, initlock, _p3key::key, lockheld, MOC_SYM, NULL, p3buf, p3errmsg(), p3lock, p3lock_init, p3MSG_DEBUG, p3MSG_ERR, p3unlock, _p3key::size, and TRUE.
Referenced by p3_rekey(), and parse_p3data().
int p3_rekey (p3keymgmt * keys)
Function:
p3_rekey
Description:
Update the key management structure after a P3 Rekey control message has been completed. This consists of releasing the oldest keys, copying the current keys to the previous key fields, and initializing the new keys.
Note that the data and control new key fields must contain the new keys to be used.
Inputs:
keys: The session key managment structure.
Outputs:
int: Status
0: OK
<0: Error
References _p3keymgmt::cnewkey, crypto_lock, _p3keymgmt::ctldec0, _p3keymgmt::ctldec1, _p3keymgmt::ctlenc0, _p3keymgmt::ctlenc1, _p3keymgmt::datdec0, _p3keymgmt::datdec1, _p3keymgmt::datenc0, _p3keymgmt::datenc1, DeleteAESCtx(), _p3keymgmt::dnewkey, _p3key::key, lockheld, MOC_SYM, NULL, p3_init_crypto(), p3buf, p3errmsg(), p3lock, p3MSG_DEBUG, p3MSG_ERR, and p3unlock.
Referenced by rekey_session().
int p3_encrypt (unsigned char * buffer, int size, unsigned int id, int key, p3keymgmt * keys)
Function:
p3_encrypt
Description:
Encrypt a buffer.
Inputs:
buffer: The buffer to be encrypted. The encrypted data is returned in this buffer.
size: The size of the buffer, in bytes, which must be a multiple of 16.
id: The ID of the P3 packet.
crypto: The session crypto type (ie. p3DATENC1, p3CTLENC0).
Outputs:
int: Status
0: OK
<0: Error
References crypto_lock, _p3keymgmt::ctlenc0, _p3keymgmt::ctlenc1, _p3keymgmt::datenc0, _p3keymgmt::datenc1, DoAES(), MERROR_lookUpErrorCode(), MOC_SYM, NULL, p3buf, p3CTLENC0, p3CTLENC1, p3DATENC0, p3DATENC1, p3errmsg(), p3lock, p3MSG_DEBUG, p3MSG_ERR, p3unlock, TRUE, and unknown_err.
Referenced by p3send_control(), and packet_handler().
int p3_decrypt (unsigned char * buffer, int size, unsigned int id, int key, p3keymgmt * keys)
Function:
p3_decrypt
Description:
Decrypt a buffer.
Inputs:
buffer: The buffer to be decrypted. The decrypted data is returned in this buffer.
size: The size of the buffer, in bytes, which must be a multiple of 16.
id: The ID of the P3 packet.
crypto: The session crypto type (ie. p3DATENC1, p3CTLENC0).
Outputs:
int: Status
0: OK
<0: Error
References crypto_lock, _p3keymgmt::ctldec0, _p3keymgmt::ctldec1, _p3keymgmt::datdec0, _p3keymgmt::datdec1, DoAES(), FALSE, MERROR_lookUpErrorCode(), MOC_SYM, NULL, p3buf, p3CTLDEC0, p3CTLDEC1, p3DATDEC0, p3DATDEC1, p3errmsg(), p3lock, p3MSG_DEBUG, p3MSG_ERR, p3unlock, and unknown_err.
Referenced by packet_handler().