Velocite Systems Protected Point to Point Solution: p3knet.h File Reference
p3knet.h File Reference
Detailed Description
Protected Point to Point network header file
Copyright (C) Velocite 2010
#include "p3kbase.h"
#include "p3ksession.h"
Data Structures
struct _p3route
struct _p3net
struct _p3packet
Defines
#define p3PKTS_NOMOD 0x00
#define p3PKTS_ADDHDR 0x01
#define p3PKTS_RMVHDR 0x02
#define p3PKTS_CONTROL 0x04
#define p3PKTS_RAWSOCK 0x08
#define p3PKTS_CHKSUM 0x10
#define p3TCP_CHECK 1
#define p3TCP_CHECK_ADD 2
#define p3GET_MTU 3
#define p3SEND_CTL 4
#define p3IP4_ID 4
#define p3IP4_SADDR 12
#define p3IP4_DADDR 16
#define p3MSS 536
#define p3EXTRA_V4 128
#define p3MSS_V4 p3MSS + p3EXTRA_V4
#define p3EXTRA_V6 148
#define p3MSS_V6 p3MSS + p3EXTRA_V6
#define P3MAXROUTE 8
#define p3PKT_SIZE 0x0000ffff
#define p3PKT_P3SRC 0x00010000
#define p3PKT_P3DST 0x00020000
Typedefs
typedef struct _p3route p3route
typedef struct _p3net p3net
typedef struct _p3packet p3packet
Functions
int init_p3net (void)
int build_p3table (p3net *net, int ipver)
int packet_handler (p3packet *pkt, void *p3sys_net)
void p3_lookup (p3packet *pkt)
unsigned char * encrypt_packet (p3session *p3sess, unsigned char *packet)
unsigned char * decrypt_packet (p3session *p3sess, unsigned char *packet)
int p3send_control (p3session *session, p3ctlmsg *cmsg)
Variables
p3route * ipv4route
p3route * ipv6route
p3host * p3hosts
Define Documentation
#define p3PKTS_NOMOD 0x00
Packet is unmodified
#define p3PKTS_ADDHDR 0x01
Packet header added (implies encryption)
Referenced by packet_handler().
#define p3PKTS_RMVHDR 0x02
Packet header removed (implies decryption)
Referenced by packet_handler().
#define p3PKTS_CONTROL 0x04
Control packet handled by P3 processing
Referenced by packet_handler().
#define p3PKTS_RAWSOCK 0x08
Packet is establishing a raw socket
Referenced by packet_handler().
#define p3PKTS_CHKSUM 0x10
Handle checksum for stack
Referenced by packet_handler().
#define p3TCP_CHECK 1
Set a TCP checksum
Referenced by p3net_utils(), and packet_handler().
#define p3TCP_CHECK_ADD 2
Set a TCP checksum for an added MSS field
Referenced by p3net_utils(), and packet_handler().
#define p3GET_MTU 3
Get the MTU for an interface
Referenced by p3net_utils(), and packet_handler().
#define p3SEND_CTL 4
Send a P3 control packet
Referenced by p3net_utils(), and p3send_control().
#define p3IP4_ID 4
IPv4 identifier field offset
Referenced by packet_handler().
#define p3IP4_SADDR 12
IPv4 source address field offset
#define p3IP4_DADDR 16
IPv4 destination address field offset
Referenced by packet_handler().
#define p3MSS 536
Minimum IPv4 segment size
Referenced by packet_handler().
#define p3EXTRA_V4 128
Extra buffer space needed for IPv4 P3 packet
Referenced by packet_handler().
#define p3MSS_V4 p3MSS + p3EXTRA_V4
Minimum IPv4 segment size
Referenced by packet_handler().
#define p3EXTRA_V6 148
Extra buffer space needed for IPv6 P3 packet
#define p3MSS_V6 p3MSS + p3EXTRA_V6
Minimum IPv6 segment size
#define P3MAXROUTE 8
Referenced by build_p3table(), and init_p3net().
#define p3PKT_SIZE 0x0000ffff
Referenced by p3net_utils(), and packet_handler().
#define p3PKT_P3SRC 0x00010000
Referenced by p3_lookup(), and packet_handler().
#define p3PKT_P3DST 0x00020000
Referenced by p3_lookup(), and packet_handler().
Typedef Documentation
typedef struct _p3route p3route
typedef struct _p3net p3net
typedef struct _p3packet p3packet
Function Documentation
int init_p3net (void)
Function:
init_p3net
Description:
Initialize the network functionality.
The P3 routing table is used to determine if a packet is to be encrypted and forwarded to a remote P3 system. There is a configuration file for all pre-defined remote P3 systems. However, there must be a mechanism for dynamic configurations. The requirements for this are:
Administrator approval
Automation where possible
Immediate use by the remote P3 system
Inputs:
None
Outputs:
int: Status
0 = OK
<0 = Error
References _p3route::nets, NULL, p3calloc, p3errmsg(), P3MAXROUTE, and p3MSG_CRIT.
Referenced by init_primary(), init_primaryplus(), and init_secondary().
int build_p3table (p3net * net, int ipver)
Function:
build_p3_table
Description:
Build the P3 routing table.
Inputs:
net: A network destination for remote P3 hosts.
ipver: The IP version of the network being defined.
Outputs:
int: Status
0 = OK
<0 = Error
>0 = Warning
References _p3net::mask, _p3net::net, _p3route::nets, _p3route::netsz, p3errmsg(), p3HST_IPV4, P3MAXROUTE, p3MSG_DEBUG, p3MSG_WARN, and _p3net::v4.
Referenced by parse_p3data().
int packet_handler (p3packet * pkt, void * p3sys_net)
Function:
packet_handler
Description:
Determine what action to perform on an intercepted packet.
If source is another P3 system, remove the ESP enhanced header
Get the appropriate key and decrypt the packet
If destination is this P3 system, decrypt and handle control message
Else, send the packet to the appropriate interface
Else, check P3 tree for destination
If the destination is another P3 system
If the packet is TCP SYN, make sure the MSS allows for P3 header requirements
Encrypt the packet, add the P3 header and return the packet to the stack
If destination is not another P3 system, return the packet to the stack
Inputs:
pkt: A p3packet structure containing information about the packet.
p3sys_net: The system network structure pointer. This is passed as void pointer and cast appropriately in the callback, p3net_utils.
Outputs:
int: Packet status
p3PKTS_NOMOD = Unmodified
p3PKTS_ADDHDR = Header added (implies encryption)
p3PKTS_RMVHDR = Header removed (implies decryption)
p3PKTS_CONTROL = Control packet handled by P3 processing
p3PKTS_RAWSOCK = Packet is establishing a Raw socket
References _p3sec_main::addr, _p3pri_main::addr, _p3keymgmt::ctldec0, _p3keymgmt::ctldec1, _p3keymgmt::datdec0, _p3keymgmt::datdec1, _p3session::flag, _p3packet::flag, host, _p3packet::host, _p3session::keymgmt, _p3ctlmsg::len, _p3session::lock, _p3ctlmsg::message, _p3packet::netdata, NULL, p3_decrypt(), p3_encrypt(), p3_lookup(), p3buf, p3CONTROL_HDR4, p3CRYPTO_ALIGN, p3CTLDEC0, p3CTLDEC1, p3DATDEC0, p3DATDEC1, p3DATENC1, p3errmsg(), p3EXTRA_V4, p3free, p3GET_MTU, _p3session::p3hdr, p3IP4_DADDR, p3IP4_ID, p3lock, p3malloc, p3MSG_CRIT, p3MSG_DEBUG, p3MSG_ERR, p3MSG_WARN, p3MSS, p3MSS_V4, p3net_utils(), p3PKT_P3DST, p3PKT_P3SRC, p3PKT_SIZE, p3PKTS_ADDHDR, p3PKTS_CHKSUM, p3PKTS_CONTROL, p3PKTS_RAWSOCK, p3PKTS_RMVHDR, p3PSS_ACT, p3PSS_REKEY, p3SEQ_DIFF, p3SESSION_HDR4, p3SET_CHECKSUM_V4, p3TCP_CHECK, p3TCP_CHECK_ADD, p3unlock, _p3packet::packet, parse_ctl_message(), _p3host::port, primain, _p3session::rID0, _p3session::rID1, secmain, _p3host::session, _p3session::sseq, start_rekeying(), _p3sec_main::v4, and _p3pri_main::v4.
void p3_lookup (p3packet * pkt)
Function:
p3_lookup
Description:
Lookup the IP addresses of a packet in the P3 routing tables.
Inputs:
pkt: A p3packet structure containing information about the packet.
Outputs:
p3host *: Remote P3 host structure where
NULL: Not found in P3 route table
Structure pointer bit 0:
0 = Source is a P3 host
1 = Destination is a P3 network
Note that this bit must be cleared by the caller
References _p3host::addr, _p3sec_main::addr, _p3pri_main::addr, _p3packet::flag, _p3host::hlist, _p3net::host, _p3packet::host, _p3net::mask, _p3net::net, _p3route::nets, _p3route::netsz, NULL, p3errmsg(), p3MSG_ERR, p3PKT_P3DST, p3PKT_P3SRC, _p3packet::packet, primain, secmain, _p3net::v4, _p3host::v4, _p3sec_main::v4, and _p3pri_main::v4.
Referenced by packet_handler().
unsigned char* encrypt_packet (p3session * p3sess, unsigned char * packet)
unsigned char* decrypt_packet (p3session * p3sess, unsigned char * packet)
int p3send_control (p3session * session, p3ctlmsg * cmsg)
Function:
p3send_control
Description:
Build a control message and send it to a remote P3 host. All encryption is performed in this function. The packet format consists of the following:
     P3 Header      P3 Ctl Header     Control Message
                                     |---Encrypted---|
                  |------------Encrypted-------------|
 IP Hdr + ESP Hdr  IP Hdr + UDP Hdr   Control Message
Note that the control message is freed in this function.
Inputs:
session: The remote host session structure
cmsg: The control message to be sent
Outputs:
int: Status:
0: OK
<0: Error
References _p3packet::flag, _p3packet::host, _p3session::host, _p3session::keymgmt, _p3ctlmsg::len, _p3session::lock, _p3ctlmsg::message, NULL, p3_encrypt(), p3buf, p3CONTROL_HDR4, p3CTLENC1, p3DATENC1, p3errmsg(), p3free, _p3session::p3hdr, p3lock, p3malloc, p3MSG_CRIT, p3MSG_DEBUG, p3net_utils(), p3SEND_CTL, p3SEQ_DIFF, p3SESSION_HDR4, p3SET_CHECKSUM_V4, p3unlock, _p3packet::packet, _p3host::port, and _p3session::sseq.
Referenced by rekey_session(), replace_key(), and start_rekeying().
Variable Documentation
p3route* ipv4route
The primary P3 route tables
p3route * ipv6route
p3host* p3hosts
The remote host table
Referenced by parse_p3data().