Velocite Systems Protected Point to Point Solution: p3kpri_session.c File Reference
p3kpri_session.c File Reference
Detailed Description
Protected Point to Point primary session
Copyright (C) Velocite 2010
The primary user session manages communications with secondary P3 systems.
#include "p3ksession.h"
#include "p3kprimary.h"
Defines
#define _p3kPRI_SS_C
Functions
int pri_session_manager ()
void key_array_error (int flag, p3session *p3sess)
void rekey_session (int flag, unsigned int key_num, p3session *p3sess)
int rekey_test_pri (unsigned char *message, int size, p3session *p3sess)
void heartbeat_answer (unsigned int time, unsigned int seqnum, p3session *p3sess)
Define Documentation
#define _p3kPRI_SS_C
Function Documentation
int pri_session_manager (void)
Function:
session_manager
Description:
Manage the primary to secondary session.
NOTE: If implemented as a continuous child process, see sendmsg, recvmsg, and cmsg for passing socket file descriptors.
Inputs:
None
Outputs:
int: Status
0 = OK
<0 = Error
void key_array_error (int flag, p3session * p3sess)
Function:
key_array_error
Description:
Handle a key array error message from the secondary session.
Inputs:
flag: Indicates the specific error
p3sess: The session structure for the current P3 session.
Outputs:
None
Referenced by parse_ctl_message().
void rekey_session (int flag, unsigned int key_num, p3session * p3sess)
Function:
rekey_session
Description:
Start using a replacement key from the secondary. The primary sends a Rekey message as acknowledgment to the secondary.
Inputs:
flag: The result flag from the secondmary
key_num: The packet ID of the first packet to use the new key
p3sess: The session structure for the current P3 session
Outputs:
None
Referenced by parse_ctl_message().
int rekey_test_pri (unsigned char * message, int size, p3session * p3sess)
Function:
rekey_test_pri
Description:
Receive a message from a secondary, reverse it and compare it to the original test message.
Inputs:
message: The message from the secondary
size: The size of the message
p3sess: The session structure for the current P3 session.
Outputs:
int: Status
0 = OK
<0 = Error
References p3errmsg(), and p3MSG_INFO.
Referenced by parse_ctl_message().
void heartbeat_answer (unsigned int time, unsigned int seqnum, p3session * p3sess)
Function:
heartbeat_answer
Description:
Handle a heartbeat answer message from a secondary.
Inputs:
time: The P3 time that the message was sent
seqnum: The sequence number of the query
p3sess: The session structure for the current P3 session.
Outputs:
None
Referenced by parse_ctl_message().