Velocite Systems Protected Point to Point Solution: p3kprimaryplus.h File Reference
p3kprimaryplus.h File Reference
Detailed Description
Protected Point to Point product primary plus secondary main functions header file
Copyright (C) Velocite 2010
#include "p3kbase.h"
#include "p3kprimary.h"
#include "p3ksecondary.h"
Functions
int init_primaryplus (void)
int priplus_parse_config (void)
Variables
p3pri_main * primain
p3sec_main * secmain
Function Documentation
int init_primaryplus (void)
Function:
init_p3primaryplus
Description:
Initialize the P3 Primary plus Secondary module by creating the basic structures for handling P3 secondary connections.
Inputs:
None
Outputs:
int: Status
0 = OK
<0 = Error
References init_p3net(), NULL, p3calloc, p3errmsg(), and p3MSG_CRIT.
int priplus_parse_config (void)
Function:
priplus_parse_config
Description:
Parse the P3 Primary configuration file.
Inputs:
None
Outputs:
int: Status
0 = OK
<0 = Error
Function:
pri_parse_config
Description:
Parse the P3 Primary plus Secondary configuration file from the P3 sysfs structures.
Inputs:
None
Outputs:
int: Status
0 = OK
<0 = Error
Referenced by main().
Variable Documentation
p3pri_main* primain
The main primary structure
The main primaryplus structure
The main primary plus secondary structure
Referenced by main(), p3_lookup(), and packet_handler().
p3sec_main* secmain
The main secondary structure