Velocite Systems Protected Point to Point Solution: p3kprimary.h File Reference
p3kprimary.h File Reference
Detailed Description
Protected Point to Point product primary main functions header file
Copyright (C) Velocite 2010
#include "p3kbase.h"
#include "p3knet.h"
Data Structures
struct _p3pri_main
Defines
#define p3MIN_IOCTL_SIZE 4
#define p3IOCMD_PID "PID"
#define p3RMT_ARSZ 256
#define p3PRI_NINFO 0x00000001
Typedefs
typedef struct _p3pri_main p3pri_main
typedef struct _p3config p3config
Functions
int init_primary (unsigned char *ramdisk)
int parse_p3data (unsigned char *buffer, int size)
void start_rekeying (p3session *session)
Variables
p3pri_main * primain
Define Documentation
#define p3MIN_IOCTL_SIZE 4
#define p3IOCMD_PID "PID"
#define p3RMT_ARSZ 256
Referenced by init_primary().
#define p3PRI_NINFO 0x00000001
Ignore informational messages
Typedef Documentation
typedef struct _p3pri_main p3pri_main
typedef struct _p3config p3config
Function Documentation
int init_primary (unsigned char * ramdisk)
Function:
init_p3primary
Description:
Initialize the P3 Primary module by creating the basic structures for handling P3 primary connections.
Inputs:
ramdisk: The location of the RAM disk area.
Outputs:
int: Status
0 = OK
<0 = Error
References _p3pri_main::array_size, init_p3net(), _p3pri_main::key_mgr, _p3key_mgr::key_serv, _p3key_mgr::lock, NULL, p3calloc, p3errmsg(), p3lock_init, p3MSG_CRIT, p3PRI_PORT, p3RMT_ARSZ, and _p3pri_main::port.
int parse_p3data (unsigned char * buffer, int size)
Function:
parse_p3data
Description:
Parse data sent from the P3 user space application in an ioctl command.
Inputs:
buffer: The data to be parsed
size: The size of the data buffer
Outputs:
int: Status
0 = OK
<0 = Critical error
>0 = Non-critical error
Function:
parse_p3data
Description:
Parse the P3 Secondary configuration file.
Inputs:
buffer: The data to be parsed
size: The size of the data buffer
Outputs:
int: Status
0 = OK
<0 = Error
>0 = Config does not exist, use defaults
void start_rekeying (p3session * session)
Function:
start_rekeying
Description:
Start the rekeying control sequence
Inputs:
p3sess: The remote P3 host session information
Outputs:
int: Status
0 = OK
<0 = Critical error
>0 = Non-critical error
References build_newkey_message(), _p3session::flag, _p3pri_main::key_mgr, _p3session::lock, NULL, p3lock, p3PSS_REKEY, p3send_control(), and p3unlock.
Referenced by packet_handler().
Variable Documentation
p3pri_main* primain
The main primary structure
The main primaryplus structure
The main primary plus secondary structure