Velocite Systems Protected Point to Point Solution: p3kprimary.c File Reference
p3kprimary.c File Reference
Detailed Description
Protected Point to Point main primary file
Copyright (C) Velocite 2010
The Velocite Systems Protected Point to Point (P3) Primary system is the master end point in a virtual point to point connection over the Internet. It listens for connections from secondary P3 systems, and when a request is accepted, establishes an IPSec encrypted session.
When an encrypted Data session is established, an encrypted Control session which is tunneled through the main session is established. This is immediately used to set new encryption keys for both the Data and Control sessions.
All runtime administration is performed from the primary P3 system. The user interface is interactive from the command line.
#include "p3kprimary.h"
#include "p3kshare.h"
#include "p3kcrypto.h"
Defines
#define _p3k_PRIMARY_C 0
Functions
int init_primary (unsigned char *ramdisk)
int parse_p3data (unsigned char *buffer, int size)
void start_rekeying (p3session *session)
Variables
p3pri_main * primain = NULL
enum ioctl_cmd iocmd
char tbuf [4092]
char * p3buf = tbuf
struct p3config * config = NULL
Define Documentation
#define _p3k_PRIMARY_C 0
Function Documentation
int init_primary (unsigned char * ramdisk)
Function:
init_p3primary
Description:
Initialize the P3 Primary module by creating the basic structures for handling P3 primary connections.
Inputs:
ramdisk: The location of the RAM disk area.
Outputs:
int: Status
0 = OK
<0 = Error
References _p3pri_main::array_size, init_p3net(), _p3pri_main::key_mgr, _p3key_mgr::key_serv, _p3key_mgr::lock, NULL, p3calloc, p3errmsg(), p3lock_init, p3MSG_CRIT, p3PRI_PORT, p3RMT_ARSZ, and _p3pri_main::port.
int parse_p3data (unsigned char * buffer, int size)
Function:
parse_p3data
Description:
Parse data sent from the P3 user space application in an ioctl command.
Inputs:
buffer: The data to be parsed
size: The size of the data buffer
Outputs:
int: Status
0 = OK
<0 = Critical error
>0 = Non-critical error
void start_rekeying (p3session * session)
Function:
start_rekeying
Description:
Start the rekeying control sequence
Inputs:
p3sess: The remote P3 host session information
Outputs:
int: Status
0 = OK
<0 = Critical error
>0 = Non-critical error
References build_newkey_message(), _p3session::flag, _p3pri_main::key_mgr, _p3session::lock, NULL, p3lock, p3PSS_REKEY, p3send_control(), and p3unlock.
Referenced by packet_handler().
Variable Documentation
p3pri_main* primain = NULL
The main primary structure
enum ioctl_cmd iocmd
ioctl_cmd defines the format of the ioctl data passed between the user and kernel space where the command meanings are:
noop: Unused
primarycfg: Configuration data for a P3 primary system
secondarycfg: Configuration data for a P3 secondary system
prihostcfg: Configuration data for a remote P3 primary system
sechostcfg: Configuration data for a remote P3 secondary system
newsession: Data for starting a new P3 session
char tbuf[4092]
Working buffer
char * p3buf = tbuf
struct p3config* config = NULL