Velocite Systems Protected Point to Point Solution: p3ksecondary.h File Reference
p3ksecondary.h File Reference
Detailed Description
Protected Point to Point product secondary main functions header file
Copyright (C) Velocite 2010
#include "p3kbase.h"
#include "p3knet.h"
Data Structures
struct _p3sec_main
Defines
#define p3SEC_FLG1 0x00000001
Typedefs
typedef struct _p3sec_main p3sec_main
Functions
int init_secondary (void)
int parse_p3data (unsigned char *buffer, int size)
Variables
p3sec_main * secmain
Define Documentation
#define p3SEC_FLG1 0x00000001
Typedef Documentation
typedef struct _p3sec_main p3sec_main
Function Documentation
int init_secondary (void)
Function:
init_p3secondary
Description:
Initialize the P3 Primary module by creating the basic structures for handling P3 secondary connections.
Inputs:
None
Outputs:
int: Status
0 = OK
<0 = Error
References init_p3net(), NULL, p3calloc, p3errmsg(), and p3MSG_CRIT.
int parse_p3data (unsigned char * buffer, int size)
Function:
parse_p3data
Description:
Parse data sent from the P3 user space application in an ioctl command.
Inputs:
buffer: The data to be parsed
size: The size of the data buffer
Outputs:
int: Status
0 = OK
<0 = Critical error
>0 = Non-critical error
Function:
parse_p3data
Description:
Parse the P3 Secondary configuration file.
Inputs:
buffer: The data to be parsed
size: The size of the data buffer
Outputs:
int: Status
0 = OK
<0 = Error
>0 = Config does not exist, use defaults
References _p3prihostcfg::addr, _p3secondarycfg::addr, _p3sec_main::addr, _p3newsession::addr, _p3sechostcfg::addr, _p3host::addr, _p3primarycfg::addr, _p3pri_main::addr, _p3primarycfg::array_size, _p3pri_main::array_size, build_p3table(), _p3sechostcfg::citime, _p3keymgmt::cnewkey, _p3newsession::ctlkey, _p3newsession::datakey, _p3sechostcfg::ditime, _p3keymgmt::dnewkey, _p3prihostcfg::flag, _p3secondarycfg::flag, _p3sec_main::flag, _p3newsession::flag, _p3session::flag, _p3host::flag, _p3sechostcfg::flag, _p3primarycfg::flag, _p3pri_main::flag, _p3sechostcfg::hb_fail, _p3host::hb_fail, _p3sechostcfg::hb_wait, _p3host::hb_wait, _p3host::hlist, _p3net::host, _p3session::host, init_session(), _p3key::key, _p3session::keymgmt, _p3subnetcfg::mask, _p3net::mask, _p3subnetcfg::net, _p3net::net, newsession, NULL, p3_get_key_size(), p3_init_crypto(), p3buf, p3calloc, p3errmsg(), p3hosts, p3HST_IPV4, p3HST_IPV6, p3HST_KTSHF, p3KTYPE_AES128, p3MSG_CRIT, p3MSG_DEBUG, p3MSG_ERR, p3MSG_WARN, p3PSS_ACT, p3PSS_KTYPE, p3SESSION_HDR4, p3SESSION_HDR6, p3SESSION_SIZE, _p3prihostcfg::port, _p3host::port, _p3primarycfg::port, _p3pri_main::port, primarycfg, primaryhostcfg, _p3sechostcfg::rk_wait, secondarycfg, secondaryhostcfg, _p3host::session, _p3prihostcfg::subnetsz, _p3sechostcfg::subnetsz, _p3prihostcfg::v4, _p3secondarycfg::v4, _p3sec_main::v4, _p3newsession::v4, _p3subnetcfg::v4, _p3net::v4, _p3sechostcfg::v4, _p3host::v4, _p3primarycfg::v4, _p3pri_main::v4, _p3prihostcfg::v6, _p3secondarycfg::v6, _p3sec_main::v6, _p3newsession::v6, _p3subnetcfg::v6, _p3net::v6, _p3sechostcfg::v6, _p3host::v6, _p3primarycfg::v6, and _p3pri_main::v6.
Variable Documentation
p3sec_main* secmain
The main secondary structure
Referenced by p3_lookup(), and packet_handler().