Velocite Systems Protected Point to Point Solution: p3ksession.h File Reference
p3ksession.h File Reference
Detailed Description
Protected Point to Point primary user interface header file
Copyright (C) Velocite 2010
#include "p3kbase.h"
#include "p3kcrypto.h"
Data Structures
struct _p3host
struct _p3session
struct _p3ctlmsg
Defines
#define p3STYPE_DATA 1
#define p3STYPE_CTL 2
#define p3MAX_MSG_SZ 1460 - 96 - 16
#define p3CMSG_KTYPE 0x0f
#define p3CMSG_SET_KEY_ARRAY 1
#define p3CMSG_ACK_KEY_ARRAY 2
#define p3CMSG_AKKERR 0x01
#define p3CMSG_AKDERR 0x02
#define p3CMSG_AKERR (p3CMSG_AKKERR | p3CMSG_AKDERR)
#define p3CMSG_REPLACE_KEY 3
#define p3CMSG_KRCIDX 0x10
#define p3CMSG_KRDIDX 0x20
#define p3CMSG_KRXMIT 0x40
#define p3CMSG_REKEY 4
#define p3CMSG_RKCKERR 0x01
#define p3CMSG_RKCIERR 0x02
#define p3CMSG_RKDKERR 0x04
#define p3CMSG_RKDIERR 0x08
#define p3CMSG_RKERR (p3CMSG_RKCKERR | p3CMSG_RKCIERR | p3CMSG_RKDKERR | p3CMSG_RKDIERR)
#define p3CMSG_REKEY_TEST 5
#define p3CMSG_HRTBEAT_QUERY 6
#define p3CMSG_HRTBEAT_ANSWER 7
#define p3CMSG_STATUS_REQ 8
#define p3CMSG_STATUS_RESP 9
#define p3CMSG_UPDATE_INFO 10
#define p3CMSG_UICODE 0x01
#define p3CMSG_UICFG 0x02
#define p3CMSG_ACK_UPDATE 11
#define p3CMSG_AUDERR 0x01
#define p3CMSG_AUUERR 0x02
#define p3CMSG_AUERR (p3CMSG_AUDERR | p3CMSG_AUUERR)
#define p3CMSG_SHUTDOWN 12
#define p3CMSG_SHRIMM 0x01
#define p3CMSG_SHRTIME 0x02
#define p3CMSG_ACK_SHUTDOWN 13
#define p3CMSG_ASACK 0x01
#define p3PRI_PORT 5653
#define p3HST_ID 0x000fffff
#define p3HST_IPVER 0x00300000
#define p3HST_IPV4 0x00100000
#define p3HST_IPV6 0x00200000
#define p3HST_ARRAY 0x00400000
#define p3HST_KTYPE 0x0f000000
#define p3HST_KTSHF 24
#define p3SEQ_DIFF 0xa65d
#define p3HDR_SIZE 8
#define p3SESSION_HDR4 (20 + p3HDR_SIZE)
#define p3SESSION_HDR6 (40 + p3HDR_SIZE)
#define p3CONTROL_HDR4 28
#define p3CONTROL_HDR6 48
#define p3PSS_KTYPE 0x0000000f
#define p3PSS_ACT 0x00000010
#define p3PSS_REKEY 0x00000020
#define p3PSS_DRDY 0x00000040
#define p3PSS_CRDY 0x00000080
#define p3SESSION_SIZE (sizeof(p3session) + (p3KMG_KEYS * sizeof(p3key)))
Typedefs
typedef struct _p3host p3host
typedef struct _p3session p3session
typedef struct _p3ctlmsg p3ctlmsg
Functions
void init_session (p3host *host, void *srcaddr)
p3ctlmsg * build_newkey_message (unsigned int flag, p3session *p3sess, p3key_mgr *key_mgr)
p3ctlmsg * build_flag_message (int type, unsigned int flag)
p3ctlmsg * build_vlen_message (int type, unsigned int flag, unsigned char *message, int len)
p3ctlmsg * build_heartbeat_message (int type, unsigned int sequence)
p3ctlmsg * build_ctl_message (int type, unsigned char *message, int len)
int parse_ctl_message (p3ctlmsg *ctlmsg, p3session *p3sess)
int pri_session_manager (void)
void key_array_error (int flag, p3session *p3sess)
void rekey_session (int flag, unsigned int key_num, p3session *p3sess)
int rekey_test_pri (unsigned char *message, int size, p3session *p3sess)
void heartbeat_answer (unsigned int time, unsigned int seqnum, p3session *p3sess)
int sec_session_manager (void)
int set_key_array (unsigned char *message, int ksize, int dsize, p3session *p3sess)
int replace_key (unsigned char *dkey, int dindex, unsigned char *ckey, int cindex, p3session *p3sess)
int rekey_test_sec (unsigned char *message, int size, p3session *p3sess)
int heartbeat_query (unsigned int time, unsigned int seqnum, p3session *p3sess)
Variables
p3session * p3sess
Define Documentation
#define p3STYPE_DATA 1
#define p3STYPE_CTL 2
#define p3MAX_MSG_SZ 1460 - 96 - 16
Referenced by build_vlen_message().
#define p3CMSG_KTYPE 0x0f
Referenced by parse_ctl_message().
#define p3CMSG_SET_KEY_ARRAY 1
Referenced by build_vlen_message(), and parse_ctl_message().
#define p3CMSG_ACK_KEY_ARRAY 2
Referenced by parse_ctl_message().
#define p3CMSG_AKKERR 0x01
#define p3CMSG_AKDERR 0x02
#define p3CMSG_AKERR (p3CMSG_AKKERR | p3CMSG_AKDERR)
Referenced by parse_ctl_message().
#define p3CMSG_REPLACE_KEY 3
Referenced by parse_ctl_message().
#define p3CMSG_KRCIDX 0x10
Referenced by parse_ctl_message().
#define p3CMSG_KRDIDX 0x20
Referenced by parse_ctl_message().
#define p3CMSG_KRXMIT 0x40
#define p3CMSG_REKEY 4
Referenced by build_vlen_message(), parse_ctl_message(), rekey_session(), and replace_key().
#define p3CMSG_RKCKERR 0x01
#define p3CMSG_RKCIERR 0x02
Referenced by replace_key().
#define p3CMSG_RKDKERR 0x04
#define p3CMSG_RKDIERR 0x08
Referenced by replace_key().
#define p3CMSG_RKERR (p3CMSG_RKCKERR | p3CMSG_RKCIERR | p3CMSG_RKDKERR | p3CMSG_RKDIERR)
Referenced by rekey_session().
#define p3CMSG_REKEY_TEST 5
Referenced by build_vlen_message(), and parse_ctl_message().
#define p3CMSG_HRTBEAT_QUERY 6
Referenced by parse_ctl_message().
#define p3CMSG_HRTBEAT_ANSWER 7
Referenced by parse_ctl_message().
#define p3CMSG_STATUS_REQ 8
Referenced by build_vlen_message(), and parse_ctl_message().
#define p3CMSG_STATUS_RESP 9
Referenced by build_vlen_message(), and parse_ctl_message().
#define p3CMSG_UPDATE_INFO 10
Referenced by build_vlen_message(), and parse_ctl_message().
#define p3CMSG_UICODE 0x01
#define p3CMSG_UICFG 0x02
#define p3CMSG_ACK_UPDATE 11
Referenced by parse_ctl_message().
#define p3CMSG_AUDERR 0x01
#define p3CMSG_AUUERR 0x02
#define p3CMSG_AUERR (p3CMSG_AUDERR | p3CMSG_AUUERR)
#define p3CMSG_SHUTDOWN 12
Referenced by parse_ctl_message().
#define p3CMSG_SHRIMM 0x01
#define p3CMSG_SHRTIME 0x02
#define p3CMSG_ACK_SHUTDOWN 13
Referenced by parse_ctl_message().
#define p3CMSG_ASACK 0x01
#define p3PRI_PORT 5653
#define p3HST_ID 0x000fffff
#define p3HST_IPVER 0x00300000
Referenced by init_session().
#define p3HST_IPV4 0x00100000
#define p3HST_IPV6 0x00200000
#define p3HST_ARRAY 0x00400000
#define p3HST_KTYPE 0x0f000000
#define p3HST_KTSHF 24
#define p3SEQ_DIFF 0xa65d
Referenced by p3send_control(), and packet_handler().
#define p3HDR_SIZE 8
#define p3SESSION_HDR4 (20 + p3HDR_SIZE)
Referenced by p3send_control(), packet_handler(), and parse_p3data().
#define p3SESSION_HDR6 (40 + p3HDR_SIZE)
Referenced by parse_p3data().
#define p3CONTROL_HDR4 28
Referenced by p3send_control(), and packet_handler().
#define p3CONTROL_HDR6 48
#define p3PSS_KTYPE 0x0000000f
Referenced by init_session(), parse_p3data(), and replace_key().
#define p3PSS_ACT 0x00000010
Referenced by packet_handler(), and parse_p3data().
#define p3PSS_REKEY 0x00000020
Referenced by packet_handler(), rekey_session(), replace_key(), and start_rekeying().
#define p3PSS_DRDY 0x00000040
#define p3PSS_CRDY 0x00000080
#define p3SESSION_SIZE (sizeof(p3session) + (p3KMG_KEYS * sizeof(p3key)))
Referenced by parse_p3data().
Typedef Documentation
typedef struct _p3host p3host
typedef struct _p3session p3session
typedef struct _p3ctlmsg p3ctlmsg
Function Documentation
void init_session (p3host * host, void * srcaddr)
Function:
init_session
Description:
Initialize a session. This allocates a new session structure and all of its fields.
Inputs:
host: The host structure for the session to be initialized.
srcaddr: The local host address. Because it can be either IPv4 or IPv6, it is passed as a void pointer.
Outputs:
None.
References _p3host::addr, _p3keymgmt::cnewkey, _p3keymgmt::dnewkey, _p3host::flag, _p3session::flag, _p3session::keymgmt, _p3session::lock, _p3session::p3hdr, p3HST_IPV4, p3HST_IPV6, p3HST_IPVER, p3HST_KTSHF, p3HST_KTYPE, p3KSIZE_AES128, p3KSIZE_AES256, p3KTYPE_AES128, p3KTYPE_AES256, p3lock_init, p3PSS_KTYPE, _p3host::session, _p3key::size, _p3session::sseq, and _p3host::v4.
Referenced by parse_p3data().
p3ctlmsg* build_newkey_message (unsigned int flag, p3session * p3sess, p3key_mgr * key_mgr)
Referenced by start_rekeying().
p3ctlmsg* build_flag_message (int type, unsigned int flag)
Function:
build_flag_message
Description:
Build a control message that only contains a flag.
Inputs:
type: P3 control message type
flag: The flag settings
Outputs:
unsigned char *: The encrypted message or NULL if there is an error.
References build_ctl_message().
p3ctlmsg* build_vlen_message (int type, unsigned int flag, unsigned char * message, int len)
Function:
build_vlen_message
Description:
Build a varilable length control message. All variable length messages except Rekey Test include a flag.
Inputs:
type: P3 control message type
flag: The flag settings
message: The variable length message
len: The length of the message
Outputs:
unsigned char *: The encrypted message or NULL if there is an error.
References build_ctl_message(), NULL, p3CMSG_REKEY, p3CMSG_REKEY_TEST, p3CMSG_SET_KEY_ARRAY, p3CMSG_STATUS_REQ, p3CMSG_STATUS_RESP, p3CMSG_UPDATE_INFO, p3errmsg(), p3MAX_MSG_SZ, and p3MSG_ERR.
Referenced by rekey_session(), and replace_key().
p3ctlmsg* build_heartbeat_message (int type, unsigned int sequence)
Function:
build_heartbeat_message
Description:
Build a heartbeat query or answer message.
Inputs:
type: P3 control message type
sequence: The heartbeat sequence number
Outputs:
unsigned char *: The encrypted message or NULL if there is an error.
References build_ctl_message(), midnight, and NULL.
p3ctlmsg* build_ctl_message (int type, unsigned char * message, int len)
Function:
build_ctl_message
Description:
Build the requested control message and encrypt it. This is called by individual control message build functions.
Inputs:
type: P3 control message type
message: Message data
len: Length of message data
Outputs:
p3ctlmsg *: The encrypted message structure or NULL if there is an error.
References _p3ctlmsg::len, _p3ctlmsg::message, NULL, and p3calloc.
Referenced by build_flag_message(), build_heartbeat_message(), and build_vlen_message().
int parse_ctl_message (p3ctlmsg * ctlmsg, p3session * p3sess)
Function:
parse_ctl_message
Description:
Parse a message and call the function to handle it. The format of the Control Messages is:
 | 4 octets | 1 octet | Variable length |
 | Size     | Command | Data            |
   where the fields are:
 Size:  The total size of the message, including the size field itself
 Command:  An 8-bit number
 Data:  The data, if any, associated with the command
The handler functions must be defined in the primary or secondary session handler, depending on which receives the message. The message handling code is only compiled if the P3 system is the receiver. All message handling is compiled for the Primary Plus Secondary P3 system.
See the P3 System Specification for details on the commands.
Inputs:
ctlmsg: The message structure, including the buffer with the size field.
p3sess: The session structure for the current P3 session.
Outputs:
int: Status
0 = OK
<0 = Error
>0 = Status from remote P3 system
References heartbeat_answer(), heartbeat_query(), key_array_error(), _p3ctlmsg::len, _p3ctlmsg::message, NULL, p3buf, p3CMSG_ACK_KEY_ARRAY, p3CMSG_ACK_SHUTDOWN, p3CMSG_ACK_UPDATE, p3CMSG_AKERR, p3CMSG_HRTBEAT_ANSWER, p3CMSG_HRTBEAT_QUERY, p3CMSG_KRCIDX, p3CMSG_KRDIDX, p3CMSG_KTYPE, p3CMSG_REKEY, p3CMSG_REKEY_TEST, p3CMSG_REPLACE_KEY, p3CMSG_SET_KEY_ARRAY, p3CMSG_SHUTDOWN, p3CMSG_STATUS_REQ, p3CMSG_STATUS_RESP, p3CMSG_UPDATE_INFO, p3errmsg(), p3KSIZE_AES128, p3KSIZE_AES256, p3KTYPE_AES128, p3KTYPE_AES256, p3MSG_DEBUG, rekey_session(), rekey_test_pri(), rekey_test_sec(), replace_key(), and set_key_array().
Referenced by packet_handler().
int pri_session_manager (void)
Function:
session_manager
Description:
Manage the primary to secondary session.
NOTE: If implemented as a continuous child process, see sendmsg, recvmsg, and cmsg for passing socket file descriptors.
Inputs:
None
Outputs:
int: Status
0 = OK
<0 = Error
void key_array_error (int flag, p3session * p3sess)
Function:
key_array_error
Description:
Handle a key array error message from the secondary session.
Inputs:
flag: Indicates the specific error
p3sess: The session structure for the current P3 session.
Outputs:
None
Referenced by parse_ctl_message().
void rekey_session (int flag, unsigned int key_num, p3session * p3sess)
Function:
rekey_session
Description:
Start using a replacement key from the secondary. The primary sends a Rekey message as acknowledgment to the secondary.
Inputs:
flag: The result flag from the secondmary
key_num: The packet ID of the first packet to use the new key
p3sess: The session structure for the current P3 session
Outputs:
None
Function:
rekey_session
Description:
Start using a replacement key from the primary.
Inputs:
flag: The result flag from the primary
key_num: The packet ID of the first packet to use the new key
p3sess: The session structure for the current P3 session
Outputs:
None
References build_vlen_message(), _p3session::flag, _p3session::keymgmt, _p3session::lock, NULL, p3_rekey(), p3CMSG_REKEY, p3CMSG_RKERR, p3errmsg(), p3lock, p3MSG_ERR, p3PSS_REKEY, p3send_control(), p3unlock, _p3session::rID0, _p3session::rID1, and _p3session::sseq.
Referenced by parse_ctl_message().
int rekey_test_pri (unsigned char * message, int size, p3session * p3sess)
Function:
rekey_test_pri
Description:
Receive a message from a secondary, reverse it and compare it to the original test message.
Inputs:
message: The message from the secondary
size: The size of the message
p3sess: The session structure for the current P3 session.
Outputs:
int: Status
0 = OK
<0 = Error
References p3errmsg(), and p3MSG_INFO.
Referenced by parse_ctl_message().
void heartbeat_answer (unsigned int time, unsigned int seqnum, p3session * p3sess)
Function:
heartbeat_answer
Description:
Handle a heartbeat answer message from a secondary.
Inputs:
time: The P3 time that the message was sent
seqnum: The sequence number of the query
p3sess: The session structure for the current P3 session.
Outputs:
None
Referenced by parse_ctl_message().
int sec_session_manager (void)
Function:
session_manager
Description:
Manage the secondary to secondary session.
NOTE: If implemented as a continuous child process, see sendmsg, recvmsg, and cmsg for passing socket file descriptors.
Inputs:
None
Outputs:
int: Status
0 = OK
<0 = Error
int set_key_array (unsigned char * message, int ksize, int dsize, p3session * p3sess)
Function:
set_key_array
Description:
Receive an array of keys from the primary. The secondary stores these in an array for when an index is used to indicate the key replacement.
Inputs:
message: The array of keys
ksize: The key size
dsize: The number of keys in the array
p3sess: The session structure for the current P3 session.
Outputs:
int: Status (see the errors for the p3CMSG_ACK_KEY_ARRAY field)
Referenced by parse_ctl_message().
int replace_key (unsigned char * dkey, int dindex, unsigned char * ckey, int cindex, p3session * p3sess)
Function:
replace_key
Description:
Replace the data and control keys from the primary using the key or index sent in the message.
Inputs:
dkey: The data key contained in the message or NULL
dindex: The data key index contained in the message or length of key
ckey: The control key contained in the message or NULL
cindex: The control key index contained in the message or length of key
p3sess: The session structure for the current P3 session.
Outputs:
int: Status (see the errors for the p3CMSG_KEY_STATUS field)
References build_vlen_message(), _p3keymgmt::cnewkey, _p3keymgmt::dnewkey, _p3session::flag, _p3key::key, _p3session::keylist, _p3session::keymgmt, _p3session::listsize, _p3session::lock, NULL, p3CMSG_REKEY, p3CMSG_RKCIERR, p3CMSG_RKDIERR, p3errmsg(), p3KSIZE_AES128, p3KSIZE_AES256, p3KTYPE_AES128, p3KTYPE_AES256, p3lock, p3MSG_ERR, p3PSS_KTYPE, p3PSS_REKEY, p3send_control(), p3unlock, and _p3session::sseq.
Referenced by parse_ctl_message().
int rekey_test_sec (unsigned char * message, int size, p3session * p3sess)
Function:
rekey_test_sec
Description:
Receive a message from the primary, reverse it and resend it.
Inputs:
message: The message from the primary
size: The size of the message
p3sess: The session structure for the current P3 session.
Outputs:
int: Status
0 = OK
<0 = Error
Referenced by parse_ctl_message().
int heartbeat_query (unsigned int time, unsigned int seqnum, p3session * p3sess)
Function:
heartbeat_query
Description:
Handle a heartbeat query message from a primary.
Inputs:
time: The P3 time that the message was sent
seqnum: The sequence number of the query
p3sess: The session structure for the current P3 session.
Outputs:
int: Status
0 = OK
<0 = Error
Referenced by parse_ctl_message().
Variable Documentation
p3session* p3sess