Velocite Systems Protected Point to Point Solution: p3ksession.c File Reference
p3ksession.c File Reference
Detailed Description
Protected Point to Point primary session
Copyright (C) Velocite 2010
The primary user session manages communications with secondary P3 systems.
#include "p3knet.h"
Functions
void init_session (p3host *host, void *srcaddr)
p3ctlmsg * build_flag_message (int type, unsigned int flag)
p3ctlmsg * build_vlen_message (int type, unsigned int flag, unsigned char *message, int len)
p3ctlmsg * build_heartbeat_message (int type, unsigned int sequence)
p3ctlmsg * build_ctl_message (int type, unsigned char *message, int len)
int parse_ctl_message (p3ctlmsg *ctlmsg, p3session *p3sess)
Variables
time_t midnight = 0
Function Documentation
void init_session (p3host * host, void * srcaddr)
Function:
init_session
Description:
Initialize a session. This allocates a new session structure and all of its fields.
Inputs:
host: The host structure for the session to be initialized.
srcaddr: The local host address. Because it can be either IPv4 or IPv6, it is passed as a void pointer.
Outputs:
None.
References _p3host::addr, _p3keymgmt::cnewkey, _p3keymgmt::dnewkey, _p3host::flag, _p3session::flag, _p3session::keymgmt, _p3session::lock, _p3session::p3hdr, p3HST_IPV4, p3HST_IPV6, p3HST_IPVER, p3HST_KTSHF, p3HST_KTYPE, p3KSIZE_AES128, p3KSIZE_AES256, p3KTYPE_AES128, p3KTYPE_AES256, p3lock_init, p3PSS_KTYPE, _p3host::session, _p3key::size, _p3session::sseq, and _p3host::v4.
Referenced by parse_p3data().
p3ctlmsg* build_flag_message (int type, unsigned int flag)
Function:
build_flag_message
Description:
Build a control message that only contains a flag.
Inputs:
type: P3 control message type
flag: The flag settings
Outputs:
unsigned char *: The encrypted message or NULL if there is an error.
References build_ctl_message().
p3ctlmsg* build_vlen_message (int type, unsigned int flag, unsigned char * message, int len)
Function:
build_vlen_message
Description:
Build a varilable length control message. All variable length messages except Rekey Test include a flag.
Inputs:
type: P3 control message type
flag: The flag settings
message: The variable length message
len: The length of the message
Outputs:
unsigned char *: The encrypted message or NULL if there is an error.
References build_ctl_message(), NULL, p3CMSG_REKEY, p3CMSG_REKEY_TEST, p3CMSG_SET_KEY_ARRAY, p3CMSG_STATUS_REQ, p3CMSG_STATUS_RESP, p3CMSG_UPDATE_INFO, p3errmsg(), p3MAX_MSG_SZ, and p3MSG_ERR.
Referenced by rekey_session(), and replace_key().
p3ctlmsg* build_heartbeat_message (int type, unsigned int sequence)
Function:
build_heartbeat_message
Description:
Build a heartbeat query or answer message.
Inputs:
type: P3 control message type
sequence: The heartbeat sequence number
Outputs:
unsigned char *: The encrypted message or NULL if there is an error.
References build_ctl_message(), midnight, and NULL.
p3ctlmsg* build_ctl_message (int type, unsigned char * message, int len)
Function:
build_ctl_message
Description:
Build the requested control message and encrypt it. This is called by individual control message build functions.
Inputs:
type: P3 control message type
message: Message data
len: Length of message data
Outputs:
p3ctlmsg *: The encrypted message structure or NULL if there is an error.
References _p3ctlmsg::len, _p3ctlmsg::message, NULL, and p3calloc.
Referenced by build_flag_message(), build_heartbeat_message(), and build_vlen_message().
int parse_ctl_message (p3ctlmsg * ctlmsg, p3session * p3sess)
Function:
parse_ctl_message
Description:
Parse a message and call the function to handle it. The format of the Control Messages is:
 | 4 octets | 1 octet | Variable length |
 | Size     | Command | Data            |
   where the fields are:
 Size:  The total size of the message, including the size field itself
 Command:  An 8-bit number
 Data:  The data, if any, associated with the command
The handler functions must be defined in the primary or secondary session handler, depending on which receives the message. The message handling code is only compiled if the P3 system is the receiver. All message handling is compiled for the Primary Plus Secondary P3 system.
See the P3 System Specification for details on the commands.
Inputs:
ctlmsg: The message structure, including the buffer with the size field.
p3sess: The session structure for the current P3 session.
Outputs:
int: Status
0 = OK
<0 = Error
>0 = Status from remote P3 system
References heartbeat_answer(), heartbeat_query(), key_array_error(), _p3ctlmsg::len, _p3ctlmsg::message, NULL, p3buf, p3CMSG_ACK_KEY_ARRAY, p3CMSG_ACK_SHUTDOWN, p3CMSG_ACK_UPDATE, p3CMSG_AKERR, p3CMSG_HRTBEAT_ANSWER, p3CMSG_HRTBEAT_QUERY, p3CMSG_KRCIDX, p3CMSG_KRDIDX, p3CMSG_KTYPE, p3CMSG_REKEY, p3CMSG_REKEY_TEST, p3CMSG_REPLACE_KEY, p3CMSG_SET_KEY_ARRAY, p3CMSG_SHUTDOWN, p3CMSG_STATUS_REQ, p3CMSG_STATUS_RESP, p3CMSG_UPDATE_INFO, p3errmsg(), p3KSIZE_AES128, p3KSIZE_AES256, p3KTYPE_AES128, p3KTYPE_AES256, p3MSG_DEBUG, rekey_session(), rekey_test_pri(), rekey_test_sec(), replace_key(), and set_key_array().
Referenced by packet_handler().
Variable Documentation
time_t midnight = 0
The time_t equivalent of the previous midnight
Referenced by build_heartbeat_message().