Velocite Systems Protected Point to Point Solution: p3ksec_session.c File Reference
p3ksec_session.c File Reference
Detailed Description
Protected Point to Point secondary session
Copyright (C) Velocite 2010
The secondary user session manages communications with primary P3 systems.
#include "p3ksession.h"
#include "p3ksecondary.h"
Defines
#define _p3kSEC_SS_C
Functions
int sec_session_manager ()
int set_key_array (unsigned char *message, int ksize, int dsize, p3session *p3sess)
int replace_key (unsigned char *dkey, int dindex, unsigned char *ckey, int cindex, p3session *p3sess)
void rekey_session (int flag, unsigned int key_num, p3session *p3sess)
int rekey_test_sec (unsigned char *message, int size, p3session *p3sess)
int heartbeat_query (unsigned int time, unsigned int seqnum, p3session *p3sess)
Define Documentation
#define _p3kSEC_SS_C
Function Documentation
int sec_session_manager (void)
Function:
session_manager
Description:
Manage the secondary to secondary session.
NOTE: If implemented as a continuous child process, see sendmsg, recvmsg, and cmsg for passing socket file descriptors.
Inputs:
None
Outputs:
int: Status
0 = OK
<0 = Error
int set_key_array (unsigned char * message, int ksize, int dsize, p3session * p3sess)
Function:
set_key_array
Description:
Receive an array of keys from the primary. The secondary stores these in an array for when an index is used to indicate the key replacement.
Inputs:
message: The array of keys
ksize: The key size
dsize: The number of keys in the array
p3sess: The session structure for the current P3 session.
Outputs:
int: Status (see the errors for the p3CMSG_ACK_KEY_ARRAY field)
Referenced by parse_ctl_message().
int replace_key (unsigned char * dkey, int dindex, unsigned char * ckey, int cindex, p3session * p3sess)
Function:
replace_key
Description:
Replace the data and control keys from the primary using the key or index sent in the message.
Inputs:
dkey: The data key contained in the message or NULL
dindex: The data key index contained in the message or length of key
ckey: The control key contained in the message or NULL
cindex: The control key index contained in the message or length of key
p3sess: The session structure for the current P3 session.
Outputs:
int: Status (see the errors for the p3CMSG_KEY_STATUS field)
References build_vlen_message(), _p3keymgmt::cnewkey, _p3keymgmt::dnewkey, _p3session::flag, _p3key::key, _p3session::keylist, _p3session::keymgmt, _p3session::listsize, _p3session::lock, NULL, p3CMSG_REKEY, p3CMSG_RKCIERR, p3CMSG_RKDIERR, p3errmsg(), p3KSIZE_AES128, p3KSIZE_AES256, p3KTYPE_AES128, p3KTYPE_AES256, p3lock, p3MSG_ERR, p3PSS_KTYPE, p3PSS_REKEY, p3send_control(), p3unlock, and _p3session::sseq.
Referenced by parse_ctl_message().
void rekey_session (int flag, unsigned int key_num, p3session * p3sess)
Function:
rekey_session
Description:
Start using a replacement key from the primary.
Inputs:
flag: The result flag from the primary
key_num: The packet ID of the first packet to use the new key
p3sess: The session structure for the current P3 session
Outputs:
None
References build_vlen_message(), _p3session::flag, _p3session::keymgmt, _p3session::lock, NULL, p3_rekey(), p3CMSG_REKEY, p3CMSG_RKERR, p3errmsg(), p3lock, p3MSG_ERR, p3PSS_REKEY, p3send_control(), p3unlock, _p3session::rID0, _p3session::rID1, and _p3session::sseq.
int rekey_test_sec (unsigned char * message, int size, p3session * p3sess)
Function:
rekey_test_sec
Description:
Receive a message from the primary, reverse it and resend it.
Inputs:
message: The message from the primary
size: The size of the message
p3sess: The session structure for the current P3 session.
Outputs:
int: Status
0 = OK
<0 = Error
Referenced by parse_ctl_message().
int heartbeat_query (unsigned int time, unsigned int seqnum, p3session * p3sess)
Function:
heartbeat_query
Description:
Handle a heartbeat query message from a primary.
Inputs:
time: The P3 time that the message was sent
seqnum: The sequence number of the query
p3sess: The session structure for the current P3 session.
Outputs:
int: Status
0 = OK
<0 = Error
Referenced by parse_ctl_message().