Velocite Systems Protected Point to Point Solution: p3linux.c File Reference
p3linux.c File Reference
Detailed Description
Protected Point to Point Linux functions file
Copyright (C) Velocite 2010
The Velocite Systems Protected Point to Point (P3) Linux functions are specific to the Linux kernel. These functions include:
Initialization
Memory mapping
IO Control
Packet interception
Cleanup
#include "p3knet.h"
Functions
void p3errmsg (int type, char *message)
int p3net_utils (int type, void *p3skb, void *p3pkt)
module_init (p3primary_init)
module_exit (p3primary_exit)
Function Documentation
void p3errmsg (int type, char * message)
Function:
p3errmsg
Description:
Handle error messages for the P3 system. The types of messages are defined in the p3kbase.h include file. They are:
Critical: Caused by system errors
Error: Caused by application errors
Warning: Does not cause application shutdown, but indicate the need for adminstrative correction
Notice: Information that is always reported, such as startup
Information: Information such as usage statistics. This may be ignored using the -I command line argument
Inputs:
type: The type of the message
message: The text of the message
Outputs:
None
References _p3util::flag, line, MSG_TIME, NULL, p3MSG_CRIT, p3MSG_DEBUG, p3MSG_ERR, p3MSG_INFO, p3MSG_NOTICE, p3MSG_WARN, and p3UTL_NINFO.
Referenced by AESALGO_blockDecrypt(), AESALGO_blockEncrypt(), AESALGO_makeAesKey(), buffer_handler(), build_p3table(), build_vlen_message(), DoAES(), getsubnetcfg(), init_kernel_comm(), init_key_serv(), init_p3net(), init_pri_ui(), init_primary(), init_primaryplus(), init_raw_socket(), init_sec_ui(), init_secondary(), main(), p3_decrypt(), p3_encrypt(), p3_get_key(), p3_init_crypto(), p3_lookup(), p3_rekey(), p3send_control(), packet_handler(), parse_ctl_message(), parse_p3data(), pri_init_config(), pri_parse_cmdline(), pri_parse_config(), priplus_parse_cmdline(), receive_ioctl(), rekey_session(), rekey_test_pri(), replace_key(), sec_init_config(), sec_parse_cmdline(), sec_parse_config(), send_ioctl(), update_prihost(), and update_sechost().
int p3net_utils (int type, void * p3skb, void * p3pkt)
Function:
p3net_utils
Description:
Handle network utility functions. These include:
Set a TCP checksum
Get the MTU size for an interface
Inputs:
type: Utility function type:
p3TCP_CHECK
p3TCP_CHECK_ADD
p3GET_MTU
p3SEND_CTL
p3skb: Socket buffer structure which is cast to the platform specific structure.
p3pkt: The packet structure, which is cast to a p3packet struture, may be used to pass or return data.
Outputs:
Status
References _p3packet::flag, _p3packet::netdata, NULL, p3GET_MTU, p3PKT_SIZE, p3SEND_CTL, p3TCP_CHECK, p3TCP_CHECK_ADD, and _p3packet::packet.
Referenced by p3send_control(), and packet_handler().
module_init (p3primary_init)
Kernel Functions:
module_init
Register the kernel module initialization routine with the Linux kernel.
module_exit
Register the kernel module exit routine with the Linux kernel.
module_exit (p3primary_exit)