Velocite Systems Protected Point to Point Solution: p3primary.c File Reference
p3primary.c File Reference
Detailed Description
Protected Point to Point main primary file
Copyright (C) Velocite 2010
The Velocite Systems Protected Point to Point (P3) Primary system is the master end point in a virtual point to point connection over the Internet. It listens for connections from secondary P3 systems, and when a request is accepted, establishes an IPSec encrypted session.
When an encrypted Data session is established, an encrypted Control session which is tunneled through the main session is established. This is immediately used to set new encryption keys for both the Data and Control sessions.
All runtime administration is performed from the primary P3 system. The user interface is interactive from the command line.
#include "p3primary.h"
#include "p3pri_key_server.h"
#include "p3pri_ui.h"
Defines
#define _p3_PRIMARY_C 0
Functions
int main (int argc, char *argv[])
int pri_parse_cmdline (int pc_argc, char *pc_argv[])
int pri_parse_config ()
int pri_init_config ()
int update_sechost (p3sechostcfg *sechost)
Variables
p3pri_main * primain = NULL
enum ioctl_cmd iocmd
char tbuf [p3BUFSIZE]
char * p3buf = tbuf
Define Documentation
#define _p3_PRIMARY_C 0
Function Documentation
int main (int argc, char * argv[])
Function:
main
Description:
Initialize the P3 Primary application, then listen for requests from secondary P3 systems.
Inputs:
argc: Number of arguments
argv: Argument vector
Outputs:
int: Status
0 = OK
<0 = Error
References _p3pri_main::config, _p3pri_main::home, init_kernel_comm(), init_pri_net(), init_pri_ui(), init_raw_socket(), init_utils(), MSG_TIME, NULL, p3buf, p3calloc, p3errmsg(), p3malloc, p3MSG_CRIT, p3PRI_CONFIG, p3PRI_HOME, pri_parse_cmdline(), and pri_parse_config().
int pri_parse_cmdline (int pc_argc, char * pc_argv[])
Function:
pri_parse_cmdline
Description:
Parse command line arguments supplied to the P3 Primary application.
Inputs:
pc_argc: Number of arguments
pc_argv: Argument vector
Outputs:
int: Status
0 = OK
<0 = Error
>0 = Informational
References _p3pri_main::config, _p3pri_main::flag, _p3pri_main::home, NULL, p3buf, p3errmsg(), p3malloc, p3MSG_CRIT, p3MSG_ERR, p3PRI_NINFO, and p3VERSION.
Referenced by main().
int pri_parse_config ()
Function:
pri_parse_config
Description:
Parse the P3 Primary configuration file. If there are errors with individual definitions, parsing continues but an error status is returned. This allows as many errors as possible to be detected in a single parsing of the configuration file.
Inputs:
None
Outputs:
int: Status
0 = OK
<0 = Error
References _p3sechostcfg::addr, _p3primarycfg::addr, _p3primarycfg::array_size, _p3pri_main::cfg_data, _p3sechostcfg::citime, _p3pri_main::cluster, _p3pri_main::config, _p3primarycfg::ctlidx_wait, _p3primarycfg::datidx_wait, _p3sechostcfg::ditime, _p3sechostcfg::flag, _p3pri_main::flag, _p3cluster::flag, _p3primarycfg::flag, getsubnetcfg(), _p3sechostcfg::hb_fail, _p3primarycfg::hb_fail, _p3sechostcfg::hb_wait, _p3primarycfg::hb_wait, _p3pri_main::home, _p3subnetcfg::id, isallnum(), line, LOCALEND, LOCALSTART, _p3util::lochost, _p3subnetcfg::mask, _p3subnetcfg::net, _p3subnetcfg::next, NULL, p3buf, p3BUFSIZE, p3calloc, p3errmsg(), p3HST_ARRAY, p3HST_ID, p3HST_IPV4, p3HST_IPV6, p3HST_KTSHF, p3KTYPE_AES128, p3KTYPE_AES256, p3MSG_CRIT, p3MSG_DEBUG, p3MSG_ERR, p3PCFG_ARSZ, p3PCFG_CIWT, p3PCFG_DIWT, p3PCFG_HBFL, p3PCFG_HBWT, p3PCFG_RKWT, p3PRI_PORT, p3PRI_RNSHF, p3utils, PATH_SEPARATOR, _p3primarycfg::port, pri_init_config(), primarycfg, _p3primarycfg::rekey_wait, _p3util::remhost, _p3sechostcfg::rk_wait, send_ioctl(), _p3sechostcfg::subnets, _p3sechostcfg::subnetsz, update_sechost(), _p3subnetcfg::v4, _p3sechostcfg::v4, _p3util::v4, _p3primarycfg::v4, _p3subnetcfg::v6, _p3sechostcfg::v6, _p3util::v6, and _p3primarycfg::v6.
Referenced by main().
int pri_init_config ()
Function:
pri_init_config
Description:
Initialize the configuration file for first time use.
Inputs:
None
Outputs:
int: Status
0 = OK
<0 = Error
References _p3pri_main::cfg_data, _p3pri_main::config, _p3pri_main::home, NULL, p3buf, p3errmsg(), p3MSG_CRIT, p3SHARE_MODE, and PATH_SEPARATOR.
Referenced by pri_parse_config().
int update_sechost (p3sechostcfg * sechost)
Function:
update_sechost
Description:
Build a remote secondary host definition to be sent to the kernel module in an ioctl buffer. The list of subnet configurations is freed as the command buffer is built.
Inputs:
sechost: The secondary host definition, which contains a list of subnets associated with it.
Outputs:
int: Status
0 = OK
<0 = Error
References _p3subnetcfg::next, NULL, p3buf, p3errmsg(), p3malloc, p3MSG_CRIT, p3MSG_ERR, p3MSG_WARN, secondaryhostcfg, send_ioctl(), _p3sechostcfg::subnets, and _p3sechostcfg::subnetsz.
Referenced by pri_parse_config().
Variable Documentation
p3pri_main* primain = NULL
The main primary structure
Referenced by main(), p3_lookup(), and packet_handler().
enum ioctl_cmd iocmd
ioctl_cmd defines the format of the ioctl data passed between the user and kernel space where the command meanings are:
noop: Unused
primarycfg: Configuration data for a P3 primary system
secondarycfg: Configuration data for a P3 secondary system
prihostcfg: Configuration data for a remote P3 primary system
sechostcfg: Configuration data for a remote P3 secondary system
datakey1: The initial data key for a new P3 session
controlkey1: The initial control key for a new P3 session
char tbuf[p3BUFSIZE]
Working buffer
char * p3buf = tbuf