Velocite Systems Protected Point to Point Solution: p3primaryplus.c File Reference
p3primaryplus.c File Reference
Detailed Description
Protected Point to Point main primaryplus file
Copyright (C) Velocite 2010
The Velocite Systems Protected Point to Point (P3) Primary system is the master end point in a virtual point to point connection over the Internet. It listens for connections from secondary P3 systems, and when a request is accepted, establishes an IPSec encrypted session.
When an encrypted Data session is established, an encrypted Control session which is tunneled through the main session is established. This is immediately used to set new encryption keys for both the Data and Control sessions.
All runtime administration is performed from the primaryplus P3 system. The user interface is interactive from the command line.
#include "p3primary.h"
#include "p3pri_key_server.h"
#include "p3pri_ui.h"
#include "p3secondary.h"
#include "p3sec_key_handler.h"
#include "p3sec_ui.h"
#include "p3primaryplus.h"
#include "p3share.h"
Defines
#define _p3_PRIMARY_C 0
#define _p3_SECONDARY_C 0
Functions
int main (int argc, char *argv[])
int priplus_parse_cmdline (int pc_argc, char *pc_argv[])
int priplus_parse_config ()
Variables
p3pri_main * primain = NULL
p3sec_main * secmain = NULL
enum ioctl_cmd iocmd
char tbuf [p3BUFSIZE]
char * p3buf = tbuf
Define Documentation
#define _p3_PRIMARY_C 0
#define _p3_SECONDARY_C 0
Function Documentation
int main (int argc, char * argv[])
Function:
main
Description:
Initialize the P3 Primary application, then listen for requests from secondary P3 systems.
Inputs:
argc: Number of arguments
argv: Argument vector
Outputs:
int: Status
0 = OK
<0 = Error
References _p3pri_main::config, _p3pri_main::home, init_kernel_comm(), init_pri_net(), init_pri_ui(), init_sec_net(), init_sec_ui(), MSG_TIME, NULL, p3buf, p3calloc, p3errmsg(), p3malloc, p3MSG_CRIT, p3PRI_CONFIG, p3PRI_HOME, priplus_parse_cmdline(), and priplus_parse_config().
int priplus_parse_cmdline (int pc_argc, char * pc_argv[])
Function:
priplus_parse_cmdline
Description:
Parse command line arguments supplied to the P3 Primary application.
Inputs:
pc_argc: Number of arguments
pc_argv: Argument vector
Outputs:
int: Status
0 = OK
<0 = Error
>0 = Informational
References _p3pri_main::config, _p3util::flag, NULL, p3buf, p3errmsg(), p3malloc, p3MSG_CRIT, p3MSG_ERR, p3utils, p3UTL_NINFO, and p3VERSION.
Referenced by main().
int priplus_parse_config (void)
Function:
priplus_parse_config
Description:
Parse the P3 Primary configuration file.
Inputs:
None
Outputs:
int: Status
0 = OK
<0 = Error
Referenced by main().
Variable Documentation
p3pri_main* primain = NULL
The main primaryplus structure
p3sec_main* secmain = NULL
The main secondary structure
Referenced by p3_lookup(), and packet_handler().
enum ioctl_cmd iocmd
ioctl_cmd defines the format of the ioctl data passed between the user and kernel space where the command meanings are:
noop: Unused
primarycfg: Configuration data for a P3 primary system
secondarycfg: Configuration data for a P3 secondary system
prihostcfg: Configuration data for a remote P3 primary system
sechostcfg: Configuration data for a remote P3 secondary system
datakey1: The initial data key for a new P3 session
controlkey1: The initial control key for a new P3 session
char tbuf[p3BUFSIZE]
Working buffer
char * p3buf = tbuf