Velocite Systems Protected Point to Point Solution: p3primary.h File Reference
p3primary.h File Reference
Detailed Description
Protected Point to Point product primary main functions header file
Copyright (C) Velocite 2010
#include "p3base.h"
#include "p3utils.h"
#include "p3net.h"
#include "p3share.h"
Data Structures
struct _p3pri_main
Defines
#define p3PRI_HOME "/usr/share/velsys/p3"
#define p3PRI_CONFIG "p3primary.conf"
#define p3PRI_NINFO 0x00000001
#define p3PRI_RNSW 0x00000002
#define p3PRI_RNHW 0x00000004
#define p3PRI_RNSHF 1
#define p3PRI_CLENABLE 0x00000010
#define p3PRI_CLDBALRR 0x00000020
#define p3PRI_CLDBALBC 0x00000040
Typedefs
typedef struct _p3pri_main p3pri_main
Functions
int pri_parse_cmdline (int argc, char *argv[])
int pri_parse_config ()
int pri_init_config ()
int update_sechost (p3sechostcfg *sechost)
Variables
p3pri_main primain
Define Documentation
#define p3PRI_HOME "/usr/share/velsys/p3"
Referenced by main().
#define p3PRI_CONFIG "p3primary.conf"
Referenced by main().
#define p3PRI_NINFO 0x00000001
Referenced by pri_parse_cmdline().
#define p3PRI_RNSW 0x00000002
#define p3PRI_RNHW 0x00000004
#define p3PRI_RNSHF 1
Referenced by pri_parse_config().
#define p3PRI_CLENABLE 0x00000010
#define p3PRI_CLDBALRR 0x00000020
#define p3PRI_CLDBALBC 0x00000040
Typedef Documentation
typedef struct _p3pri_main p3pri_main
Function Documentation
int pri_parse_cmdline (int pc_argc, char * pc_argv[])
Function:
pri_parse_cmdline
Description:
Parse command line arguments supplied to the P3 Primary application.
Inputs:
pc_argc: Number of arguments
pc_argv: Argument vector
Outputs:
int: Status
0 = OK
<0 = Error
>0 = Informational
References _p3pri_main::config, _p3pri_main::flag, _p3pri_main::home, NULL, p3buf, p3errmsg(), p3malloc, p3MSG_CRIT, p3MSG_ERR, p3PRI_NINFO, and p3VERSION.
Referenced by main().
int pri_parse_config ()
Function:
pri_parse_config
Description:
Parse the P3 Primary configuration file. If there are errors with individual definitions, parsing continues but an error status is returned. This allows as many errors as possible to be detected in a single parsing of the configuration file.
Inputs:
None
Outputs:
int: Status
0 = OK
<0 = Error
References _p3sechostcfg::addr, _p3primarycfg::addr, _p3primarycfg::array_size, _p3pri_main::cfg_data, _p3sechostcfg::citime, _p3pri_main::cluster, _p3pri_main::config, _p3primarycfg::ctlidx_wait, _p3primarycfg::datidx_wait, _p3sechostcfg::ditime, _p3sechostcfg::flag, _p3pri_main::flag, _p3cluster::flag, _p3primarycfg::flag, getsubnetcfg(), _p3sechostcfg::hb_fail, _p3primarycfg::hb_fail, _p3sechostcfg::hb_wait, _p3primarycfg::hb_wait, _p3pri_main::home, _p3subnetcfg::id, isallnum(), line, LOCALEND, LOCALSTART, _p3util::lochost, _p3subnetcfg::mask, _p3subnetcfg::net, _p3subnetcfg::next, NULL, p3buf, p3BUFSIZE, p3calloc, p3errmsg(), p3HST_ARRAY, p3HST_ID, p3HST_IPV4, p3HST_IPV6, p3HST_KTSHF, p3KTYPE_AES128, p3KTYPE_AES256, p3MSG_CRIT, p3MSG_DEBUG, p3MSG_ERR, p3PCFG_ARSZ, p3PCFG_CIWT, p3PCFG_DIWT, p3PCFG_HBFL, p3PCFG_HBWT, p3PCFG_RKWT, p3PRI_PORT, p3PRI_RNSHF, p3utils, PATH_SEPARATOR, _p3primarycfg::port, pri_init_config(), primarycfg, _p3primarycfg::rekey_wait, _p3util::remhost, _p3sechostcfg::rk_wait, send_ioctl(), _p3sechostcfg::subnets, _p3sechostcfg::subnetsz, update_sechost(), _p3subnetcfg::v4, _p3sechostcfg::v4, _p3util::v4, _p3primarycfg::v4, _p3subnetcfg::v6, _p3sechostcfg::v6, _p3util::v6, and _p3primarycfg::v6.
Referenced by main().
int pri_init_config ()
Function:
pri_init_config
Description:
Initialize the configuration file for first time use.
Inputs:
None
Outputs:
int: Status
0 = OK
<0 = Error
References _p3pri_main::cfg_data, _p3pri_main::config, _p3pri_main::home, NULL, p3buf, p3errmsg(), p3MSG_CRIT, p3SHARE_MODE, and PATH_SEPARATOR.
Referenced by pri_parse_config().
int update_sechost (p3sechostcfg * sechost)
Function:
update_sechost
Description:
Build a remote secondary host definition to be sent to the kernel module in an ioctl buffer. The list of subnet configurations is freed as the command buffer is built.
Inputs:
sechost: The secondary host definition, which contains a list of subnets associated with it.
Outputs:
int: Status
0 = OK
<0 = Error
References _p3subnetcfg::next, NULL, p3buf, p3errmsg(), p3malloc, p3MSG_CRIT, p3MSG_ERR, p3MSG_WARN, secondaryhostcfg, send_ioctl(), _p3sechostcfg::subnets, and _p3sechostcfg::subnetsz.
Referenced by pri_parse_config().
Variable Documentation
p3pri_main primain
The main primary structure
The main primaryplus structure
The main primary plus secondary structure