Velocite Systems Protected Point to Point Solution: p3pri_session.c File Reference
p3pri_session.c File Reference
#include "p3session.h"
#include "p3pri_key_server.h"
#include "p3primary.h"
Defines
#define _p3PRI_SS_C
Functions
int init_pri_session ()
int pri_session_manager ()
void key_array_error (int flag)
void replace_key_error (int flag)
int rekey_test_pri (unsigned char *message, int size)
void heartbeat_answer (int sec, int subsec, unsigned int seqnum)
Detailed Description
Protected Point to Point primary session
Copyright (C) Velocite 2010
The primary user session manages communications with secondary P3 systems.
Define Documentation
#define _p3PRI_SS_C
Function Documentation
int init_pri_session ()
Function:
init_pri_session
Description:
Initialize the primary to secondary session.
Inputs:
None
Outputs:
int: Status
0 = OK
<0 = Error
int pri_session_manager ()
Function:
session_manager
Description:
Manage the primary to secondary session.
NOTE: If implemented as a continuous child process, see sendmsg, recvmsg, and cmsg for passing socket file descriptors.
Inputs:
None
Outputs:
int: Status
0 = OK
<0 = Error
void key_array_error (int flag)
Function:
key_array_error
Description:
Handle a key array error message from the secondary session.
Inputs:
flag: Indicates the specific error
Outputs:
None
Referenced by recv_ctl_message().
void replace_key_error (int flag)
Function:
replace_key_error
Description:
Handle a key array error message from the secondary session.
Inputs:
flag: Indicates the specific error
Outputs:
None
Referenced by recv_ctl_message().
int rekey_test_pri (unsigned char * message, int size)
Function:
rekey_test_pri
Description:
Receive a message from a secondary, reverse it and compare it to the original test message.
Inputs:
message: The message from the secondary
size: The size of the message
Outputs:
int: Status
0 = OK
<0 = Error
Referenced by recv_ctl_message().
void heartbeat_answer (int sec, int subsec, unsigned int seqnum)
Function:
heartbeat_answer
Description:
Handle a heartbeat answer message from a secondary.
Inputs:
sec: The number of seconds after midnight the message was sent
subsec: The sub second time the message was sent
seqnum: The sequence number of the query
Outputs:
None
Referenced by recv_ctl_message().