Velocite Systems Protected Point to Point Solution: p3pri_ui.h File Reference
p3pri_ui.h File Reference
Detailed Description
Protected Point to Point primary user interface header file
Copyright (C) Velocite 2010
#include "p3base.h"
Data Structures
struct _p3pri_ui
Defines
#define PRI_FIFO_IN "pui_in"
#define PRI_FIFO_OUT "pui_out"
Typedefs
typedef struct _p3pri_ui p3pri_ui
Functions
int init_pri_ui ()
int pri_ui_handler ()
Variables
p3pri_ui * pri_ui
Define Documentation
#define PRI_FIFO_IN "pui_in"
Primary read FIFO name
#define PRI_FIFO_OUT "pui_out"
Primary write FIFO name
Typedef Documentation
typedef struct _p3pri_ui p3pri_ui
Function Documentation
int init_pri_ui ()
Function:
init_pri_ui
Description:
Initialize the primary user interface. The P3 primary application does not interact directly with an administrator, the p3admin application does. Then that application communicates changes to the P3 primary through a FIFO. The P3 primary interface then updates the configuration, and if appropriate, dynamically updates the application.
Inputs:
None
Outputs:
int: Status
0 = OK
<0 = Error
References NULL, p3buf, p3calloc, p3errmsg(), p3MSG_CRIT, and pri_ui_handler().
Referenced by main().
int pri_ui_handler ()
Function:
pri_ui_handler
Description:
Wait for input from the administrator interface through a FIFO. The P3 primary interface then updates the configuration, and if appropriate, dynamically updates the application.
Inputs:
None
Outputs:
int: Status
0 = OK
<0 = Error
Referenced by init_pri_ui().
Variable Documentation
p3pri_ui* pri_ui
Global variable usage