Velocite Systems Protected Point to Point Solution: p3pri_key_server.c File Reference
p3pri_key_server.c File Reference
Detailed Description
Protected Point to Point primary key server file
Copyright (C) Velocite 2010
The key server manages true random keys for encryption. It constantly produces keys which are placed on the circular buffer shared with the kernel module. Whenever the circular buffer has slots for keys the key server fills all slots with new keys.
#include "p3pri_key_server.h"
#include "p3primary.h"
#include "p3utils.h"
Defines
#define _p3PRI_KEY_SERVER_C
Functions
int init_key_serv (p3key_serv *kserv)
int buffer_handler ()
Variables
p3key_serv * key_serv = NULL
p3key keysrv_key
p3key * ks_key = &keysrv_key
Define Documentation
#define _p3PRI_KEY_SERVER_C
Function Documentation
int init_key_serv (p3key_serv * kserv)
Function:
init_key_serv
Description:
Initialize the key server data structure and the circular buffer shared with the kernel module. This memory includes the key server data structure at the beginning, followed by the circular buffer.
The circular buffer is an array of pointers to keys, because the keys used by different sessions can be different sizes. The kernel module can use a key if the head and tail indexes are not equal.
Inputs:
kserv: The location of the key server structure in the mmap'ed buffer.
Outputs:
int: Status
0 = OK
<0 = Error
References buffer_handler(), NULL, p3errmsg(), p3MAX_KSIZE, p3MSG_ERR, and _p3key::size.
Referenced by init_kernel_comm().
int buffer_handler ()
Function:
buffer_handler
Description:
Handle the circular buffer shared with the kernel module. This is done when the tail index is not equal to the head index. In this case, a new key is created in the current head slot and the head pointer is incremented to indicate that the key is available.
Inputs:
None
Outputs:
int: Status
0 = OK
<0 = Error
References _p3key_serv::cbuf_sz, _p3key_serv::head, _p3key::key, NULL, p3_get_key(), p3buf, p3errmsg(), p3MSG_DEBUG, _p3key::size, and _p3key_serv::tail.
Referenced by init_key_serv().
Variable Documentation
p3key_serv* key_serv = NULL
The main key server data structure
Referenced by p3_get_key().
p3key keysrv_key
The key server uses a single key structure
p3key * ks_key = &keysrv_key