Velocite Systems Protected Point to Point Solution: p3profile.c File Reference
p3profile.c File Reference
#include <malloc.h>
#include <stdio.h>
#include <errno.h>
#include <ctype.h>
#include <stdlib.h>
#include <string.h>
#include <sys/socket.h>
#include <arpa/inet.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <fcntl.h>
#include <unistd.h>
#include "p3base.h"
#include "p3primary.h"
#include "p3pri_net.h"
#include "p3secondary.h"
#include "p3sec_net.h"
#include <sys/mman.h>
Defines
#define TRUE 1
#define FALSE 0
#define PAGESIZE 4096
Typedefs
typedef struct stat Stat
Functions
int isallip (char *)
int isallnum (char *)
void p3errmsg (int, char *)
int main (int argc, char **argv)
Variables
int current_ip = 0
void * map
void * pri_map = NULL
void * sec_map = NULL
int line = 0
Define Documentation
#define TRUE 1
Referenced by main(), p3_encrypt(), and p3_init_crypto().
#define FALSE 0
Referenced by AESALGO_blockEncrypt(), p3_decrypt(), and p3_init_crypto().
#define PAGESIZE 4096
Typedef Documentation
typedef struct stat Stat
Function Documentation
int isallip (char * parm)
Referenced by main().
int isallnum (char * parm)
Function:
isallnum
Description:
Validate that a string is only base 10 digits.
Inputs:
parm: The string to be tested.
Outputs:
int: Status
0 = Only digits
<0 = String contains non-digits
Referenced by main(), pri_parse_config(), and sec_parse_config().
void p3errmsg (int type, char * message)
Function:
p3errmsg
Description:
Handle error messages for the P3 system. The types of messages are defined in the p3base.h include file. They are:
Critical: Caused by system errors
Error: Caused by application errors
Warning: Does not cause application shutdown, but indicate the need for adminstrative correction
Notice: Information that is always reported, such as startup
Information: Information such as usage statistics. This may be ignored using the -I command line argument
Inputs:
type: The type of the message
message: The text of the message
Outputs:
None
Function:
p3errmsg
Description:
Handle error messages for the P3 system. The types of messages are defined in the p3kbase.h include file. They are:
Critical: Caused by system errors
Error: Caused by application errors
Warning: Does not cause application shutdown, but indicate the need for adminstrative correction
Notice: Information that is always reported, such as startup
Information: Information such as usage statistics. This may be ignored using the -I command line argument
Inputs:
type: The type of the message
message: The text of the message
Outputs:
None
References line, MSG_TIME, NULL, p3MSG_CRIT, p3MSG_DEBUG, p3MSG_ERR, p3MSG_INFO, p3MSG_NOTICE, and p3MSG_WARN.
Referenced by AESALGO_blockDecrypt(), AESALGO_blockEncrypt(), AESALGO_makeAesKey(), buffer_handler(), build_p3table(), build_vlen_message(), DoAES(), getsubnetcfg(), init_kernel_comm(), init_key_serv(), init_p3net(), init_pri_ui(), init_primary(), init_primaryplus(), init_raw_socket(), init_sec_ui(), init_secondary(), main(), p3_decrypt(), p3_encrypt(), p3_get_key(), p3_init_crypto(), p3_lookup(), p3_rekey(), p3send_control(), packet_handler(), parse_ctl_message(), parse_p3data(), pri_init_config(), pri_parse_cmdline(), pri_parse_config(), priplus_parse_cmdline(), receive_ioctl(), rekey_session(), rekey_test_pri(), replace_key(), sec_init_config(), sec_parse_cmdline(), sec_parse_config(), send_ioctl(), update_prihost(), and update_sechost().
int main (int argc, char ** argv)
References _p3pri_main::cfg_data, current_ip, isallip(), isallnum(), line, NULL, p3buf, p3errmsg(), p3MSG_CRIT, primain, and TRUE.
Variable Documentation
int current_ip = 0
Referenced by main().
void* map
void* pri_map = NULL
void* sec_map = NULL
int line = 0
Referenced by main(), p3errmsg(), pri_parse_config(), and sec_parse_config().