Velocite Systems Protected Point to Point Solution: p3session.c File Reference
p3session.c File Reference
#include "p3session.h"
Functions
int send_ctl_message (int type, unsigned char *message, int len, p3session *p3sess)
int recv_ctl_message (unsigned char *message)
Detailed Description
Protected Point to Point primary session
Copyright (C) Velocite 2010
The primary user session manages communications with secondary P3 systems.
Function Documentation
int send_ctl_message (int type, unsigned char * message, int len, p3session * p3sess)
Function:
send_ctl_message
Description:
Manage the primary to secondary session.
NOTE: If implemented as a continuous child process, see sendmsg, recvmsg, and cmsg for passing socket file descriptors.
Inputs:
type: P3 control message type
message: Message data
len: Length of message data
sess: Session structure
Outputs:
int: Status
0 = OK
<0 = Error
References _p3session::ctlhdr, _p3session::hdrlen, and p3malloc.
int recv_ctl_message (unsigned char * message)
Function:
recv_ctl_message
Description:
Parse a message and call the function to handle it. The format of the Control Messages is:
 | 4 octets | 1 octet | Variable length |
 | Size     | Command | Data            |
   where the fields are:
 Size:  The total size of the message, including the size field itself
 Command:  An 8-bit number
 Data:  The data, if any, associated with the command
The handler functions must be defined in the primary or secondary session handler, depending on which receives the message. The message handling code is only compiled if the P3 system is the receiver. All message handling is compiled for the Primary Plus Secondary P3 system.
See the P3 System Specification for details on the commands.
Inputs:
message: The full message buffer including the size field.
Outputs:
int: Status
0 = OK
<0 = Error
>0 = Status from remote P3 system
References heartbeat_answer(), heartbeat_query(), key_array_error(), p3CMSG_ACK_KEY_ARRAY, p3CMSG_ACK_SHUTDOWN, p3CMSG_ACK_UPDATE, p3CMSG_AKERR, p3CMSG_HRTBEAT_ANSWER, p3CMSG_HRTBEAT_QUERY, p3CMSG_KEY_STATUS, p3CMSG_KRCIDX, p3CMSG_KRDIDX, p3CMSG_KSERR, p3CMSG_KTYPE, p3CMSG_REKEY, p3CMSG_REKEY_TEST, p3CMSG_REPLACE_KEY, p3CMSG_SET_KEY_ARRAY, p3CMSG_SHUTDOWN, p3CMSG_STATUS_REQ, p3CMSG_STATUS_RESP, p3CMSG_UPDATE_INFO, p3KSIZE_AES128, p3KSIZE_AES256, p3KTYPE_AES128, p3KTYPE_AES256, p3STYPE_CTL, p3STYPE_DATA, rekey_session(), rekey_test_pri(), rekey_test_sec(), replace_key(), replace_key_error(), replace_key_index(), and set_key_array().