Velocite Systems Protected Point to Point Solution: p3secondary.c File Reference
p3secondary.c File Reference
Detailed Description
Protected Point to Point main secondary file
Copyright (C) Velocite 2010
The Velocite Systems Protected Point to Point (P3) Secondary system is the client end point in a virtual point to point connection over the Internet. It requests a connections from a primary P3 system, and when a request is accepted, establishes an IPSec encrypted session.
When an encrypted Data session is established, an encrypted Control session which is tunneled through the main session is established. This is immediately used to set new encryption keys for both the Data and Control sessions.
All runtime administration is performed from the primary P3 system. The user interface for initial setup is interactive from the command line.
#include "p3secondary.h"
#include "p3sec_key_handler.h"
#include "p3sec_ui.h"
Defines
#define _p3_SECONDARY_C 0
Functions
int main (int argc, char *argv[])
int sec_parse_cmdline (int pc_argc, char *pc_argv[])
int sec_parse_config ()
int sec_init_config ()
int update_prihost (p3prihostcfg *prihost)
Variables
p3sec_main * secmain = NULL
enum ioctl_cmd iocmd
char tbuf [p3BUFSIZE]
char * p3buf = tbuf
Define Documentation
#define _p3_SECONDARY_C 0
Function Documentation
int main (int argc, char * argv[])
Function:
main
Description:
Initialize the P3 Secondary application, then listen for requests from secondary P3 systems.
Inputs:
argc: Number of arguments
argv: Argument vector
Outputs:
int: Status
0 = OK
<0 = Error
References _p3sec_main::config, _p3sec_main::home, init_kernel_comm(), init_raw_socket(), init_sec_net(), init_sec_ui(), init_utils(), MSG_TIME, NULL, p3buf, p3calloc, p3errmsg(), p3malloc, p3MSG_CRIT, p3MSG_DEBUG, p3SEC_CONFIG, p3SEC_HOME, sec_parse_cmdline(), and sec_parse_config().
int sec_parse_cmdline (int pc_argc, char * pc_argv[])
Function:
sec_parse_cmdline
Description:
Parse command line arguments supplied to the P3 Secondary application.
Inputs:
pc_argc: Number of arguments
pc_argv: Argument vector
Outputs:
int: Status
0 = OK
<0 = Error
>0 = Informational
References _p3sec_main::config, _p3util::flag, _p3sec_main::home, NULL, p3buf, p3errmsg(), p3malloc, p3MSG_CRIT, p3MSG_ERR, p3utils, p3UTL_NINFO, and p3VERSION.
Referenced by main().
int sec_parse_config ()
Function:
sec_parse_config
Description:
Parse the P3 Secondary configuration file.
Inputs:
None
Outputs:
int: Status
0 = OK
<0 = Error
>0 = Config does not exist, use defaults
References _p3prihostcfg::addr, _p3secondarycfg::addr, _p3sec_main::cfg_data, _p3sec_main::cluster, _p3sec_main::config, _p3prihostcfg::flag, _p3cluster::flag, _p3secondarycfg::flag, getsubnetcfg(), _p3sec_main::home, _p3subnetcfg::id, isallnum(), line, LOCALEND, LOCALSTART, _p3util::lochost, _p3subnetcfg::mask, _p3subnetcfg::net, _p3subnetcfg::next, NULL, p3buf, p3BUFSIZE, p3calloc, p3errmsg(), p3HST_ID, p3HST_IPV4, p3HST_IPV6, p3MSG_CRIT, p3MSG_DEBUG, p3MSG_ERR, p3PRI_PORT, p3utils, PATH_SEPARATOR, _p3prihostcfg::port, _p3util::remhost, sec_init_config(), secondarycfg, send_ioctl(), _p3prihostcfg::subnets, _p3prihostcfg::subnetsz, update_prihost(), _p3subnetcfg::v4, _p3prihostcfg::v4, _p3util::v4, _p3secondarycfg::v4, _p3subnetcfg::v6, _p3prihostcfg::v6, _p3util::v6, and _p3secondarycfg::v6.
Referenced by main().
int sec_init_config ()
Function:
init_config
Description:
Initialize the configuration file for first time use.
Inputs:
None
Outputs:
int: Status
0 = OK
<0 = Error
References _p3sec_main::cfg_data, _p3sec_main::config, _p3sec_main::home, NULL, p3buf, p3errmsg(), p3MSG_CRIT, p3SHARE_MODE, and PATH_SEPARATOR.
Referenced by sec_parse_config().
int update_prihost (p3prihostcfg * prihost)
Function:
update_prihost
Description:
Build a remote primary host definition to be sent to the kernel module in an ioctl buffer. The list of subnet configurations is freed as the command buffer is built.
Inputs:
prihost: The primary host definition, which contains a list of subnets associated with it.
Outputs:
int: Status
0 = OK
<0 = Error
References _p3subnetcfg::next, NULL, p3buf, p3errmsg(), p3malloc, p3MSG_CRIT, p3MSG_ERR, p3MSG_WARN, primaryhostcfg, send_ioctl(), _p3prihostcfg::subnets, and _p3prihostcfg::subnetsz.
Referenced by sec_parse_config().
Variable Documentation
p3sec_main* secmain = NULL
The main secondary structure
enum ioctl_cmd iocmd
ioctl_cmd defines the format of the ioctl data passed between the user and kernel space where the command meanings are:
noop: Unused
primarycfg: Configuration data for a P3 primary system
secondarycfg: Configuration data for a P3 secondary system
prihostcfg: Configuration data for a remote P3 primary system
sechostcfg: Configuration data for a remote P3 secondary system
datakey1: The initial data key for a new P3 session
controlkey1: The initial control key for a new P3 session
char tbuf[p3BUFSIZE]
Working buffer
char * p3buf = tbuf