Velocite Systems Protected Point to Point Solution: p3secondary.h File Reference
p3secondary.h File Reference
Detailed Description
Protected Point to Point product secondary main functions header file
Copyright (C) Velocite 2010
#include "p3base.h"
#include "p3utils.h"
#include "p3net.h"
#include "p3share.h"
Data Structures
struct _p3sec_main
Defines
#define p3SEC_HOME "/usr/share/velsys/p3"
#define p3SEC_CONFIG "p3secondary.conf"
#define p3SEC_NINFO 0x00000001
#define p3SCF_CLENABLE 0x00000002
#define p3SCF_CLDBALRR 0x00000004
#define p3SCF_CLDBALBC 0x00000008
Typedefs
typedef struct _p3sec_main p3sec_main
Functions
int sec_parse_cmdline (int argc, char *argv[])
int sec_parse_config ()
int sec_init_config ()
int update_prihost (p3prihostcfg *prihost)
Variables
p3sec_main secmain
Define Documentation
#define p3SEC_HOME "/usr/share/velsys/p3"
Referenced by main().
#define p3SEC_CONFIG "p3secondary.conf"
Referenced by main().
#define p3SEC_NINFO 0x00000001
#define p3SCF_CLENABLE 0x00000002
#define p3SCF_CLDBALRR 0x00000004
#define p3SCF_CLDBALBC 0x00000008
Typedef Documentation
typedef struct _p3sec_main p3sec_main
Function Documentation
int sec_parse_cmdline (int pc_argc, char * pc_argv[])
Function:
sec_parse_cmdline
Description:
Parse command line arguments supplied to the P3 Secondary application.
Inputs:
pc_argc: Number of arguments
pc_argv: Argument vector
Outputs:
int: Status
0 = OK
<0 = Error
>0 = Informational
References _p3sec_main::config, _p3util::flag, _p3sec_main::home, NULL, p3buf, p3errmsg(), p3malloc, p3MSG_CRIT, p3MSG_ERR, p3utils, p3UTL_NINFO, and p3VERSION.
Referenced by main().
int sec_parse_config ()
Function:
sec_parse_config
Description:
Parse the P3 Secondary configuration file.
Inputs:
None
Outputs:
int: Status
0 = OK
<0 = Error
>0 = Config does not exist, use defaults
References _p3prihostcfg::addr, _p3secondarycfg::addr, _p3sec_main::cfg_data, _p3sec_main::cluster, _p3sec_main::config, _p3prihostcfg::flag, _p3cluster::flag, _p3secondarycfg::flag, getsubnetcfg(), _p3sec_main::home, _p3subnetcfg::id, isallnum(), line, LOCALEND, LOCALSTART, _p3util::lochost, _p3subnetcfg::mask, _p3subnetcfg::net, _p3subnetcfg::next, NULL, p3buf, p3BUFSIZE, p3calloc, p3errmsg(), p3HST_ID, p3HST_IPV4, p3HST_IPV6, p3MSG_CRIT, p3MSG_DEBUG, p3MSG_ERR, p3PRI_PORT, p3utils, PATH_SEPARATOR, _p3prihostcfg::port, _p3util::remhost, sec_init_config(), secondarycfg, send_ioctl(), _p3prihostcfg::subnets, _p3prihostcfg::subnetsz, update_prihost(), _p3subnetcfg::v4, _p3prihostcfg::v4, _p3util::v4, _p3secondarycfg::v4, _p3subnetcfg::v6, _p3prihostcfg::v6, _p3util::v6, and _p3secondarycfg::v6.
Referenced by main().
int sec_init_config ()
Function:
init_config
Description:
Initialize the configuration file for first time use.
Inputs:
None
Outputs:
int: Status
0 = OK
<0 = Error
References _p3sec_main::cfg_data, _p3sec_main::config, _p3sec_main::home, NULL, p3buf, p3errmsg(), p3MSG_CRIT, p3SHARE_MODE, and PATH_SEPARATOR.
Referenced by sec_parse_config().
int update_prihost (p3prihostcfg * prihost)
Function:
update_prihost
Description:
Build a remote primary host definition to be sent to the kernel module in an ioctl buffer. The list of subnet configurations is freed as the command buffer is built.
Inputs:
prihost: The primary host definition, which contains a list of subnets associated with it.
Outputs:
int: Status
0 = OK
<0 = Error
References _p3subnetcfg::next, NULL, p3buf, p3errmsg(), p3malloc, p3MSG_CRIT, p3MSG_ERR, p3MSG_WARN, primaryhostcfg, send_ioctl(), _p3prihostcfg::subnets, and _p3prihostcfg::subnetsz.
Referenced by sec_parse_config().
Variable Documentation
p3sec_main secmain
The main secondary structure