Velocite Systems Protected Point to Point Solution: p3sec_ui.h File Reference
p3sec_ui.h File Reference
Detailed Description
Protected Point to Point secondary user interface header file
Copyright (C) Velocite 2010
#include "p3base.h"
Data Structures
struct _p3sec_ui
Defines
#define SEC_FIFO_IN "sui_in"
#define SEC_FIFO_OUT "sui_out"
Typedefs
typedef struct _p3sec_ui p3sec_ui
Functions
int init_sec_ui ()
int sec_ui_handler ()
Variables
p3sec_ui * sec_ui
Define Documentation
#define SEC_FIFO_IN "sui_in"
Secondary read FIFO name
#define SEC_FIFO_OUT "sui_out"
Secondary write FIFO name
Typedef Documentation
typedef struct _p3sec_ui p3sec_ui
Function Documentation
int init_sec_ui ()
Function:
init_sec_ui
Description:
Initialize the secondary user interface.
Inputs:
None
Outputs:
int: Status
0 = OK
<0 = Error
References NULL, p3buf, p3calloc, p3errmsg(), p3MSG_CRIT, and sec_ui_handler().
Referenced by main().
int sec_ui_handler ()
Function:
sec_ui_handler
Description:
Wait for input from the administrator interface through a FIFO. The P3 secondary interface then updates the configuration, and if appropriate, dynamically updates the application.
Inputs:
None
Outputs:
int: Status
0 = OK
<0 = Error
Referenced by init_sec_ui().
Variable Documentation
p3sec_ui* sec_ui
Global variable usage