Velocite Systems Protected Point to Point Solution: p3session.h File Reference
p3session.h File Reference
#include "p3base.h"
#include "p3crypto.h"
#include <netinet/ip.h>
#include <netinet/ip6.h>
Data Structures
struct _p3session
struct _p3route
Defines
#define p3KTYPE_AES128 1
#define p3KSIZE_AES128 (128 >> 3)
#define p3KTYPE_AES256 2
#define p3KSIZE_AES256 (256 >> 3)
#define p3STYPE_DATA 1
#define p3STYPE_CTL 2
#define p3CMSG_KTYPE 0x0f
#define p3CMSG_SET_KEY_ARRAY 1
#define p3CMSG_ACK_KEY_ARRAY 2
#define p3CMSG_AKKERR 0x01
#define p3CMSG_AKDERR 0x02
#define p3CMSG_AKERR (p3CMSG_AKKERR | p3CMSG_AKDERR)
#define p3CMSG_REPLACE_KEY 3
#define p3CMSG_KRDIDX 0x10
#define p3CMSG_KRCIDX 0x20
#define p3CMSG_KRXMIT 0x40
#define p3CMSG_KEY_STATUS 4
#define p3CMSG_KSCKERR 0x01
#define p3CMSG_KSCIERR 0x02
#define p3CMSG_KSDKERR 0x04
#define p3CMSG_KSDIERR 0x08
#define p3CMSG_KSERR (p3CMSG_KSCKERR | p3CMSG_KSCIERR | p3CMSG_KSDKERR | p3CMSG_KSDIERR)
#define p3CMSG_REKEY 5
#define p3CMSG_REKEY_TEST 6
#define p3CMSG_HRTBEAT_QUERY 7
#define p3CMSG_HRTBEAT_ANSWER 8
#define p3CMSG_STATUS_REQ 9
#define p3CMSG_STATUS_RESP 10
#define p3CMSG_UPDATE_INFO 11
#define p3CMSG_UICODE 0x01
#define p3CMSG_UICFG 0x02
#define p3CMSG_ACK_UPDATE 12
#define p3CMSG_AUDERR 0x01
#define p3CMSG_AUUERR 0x02
#define p3CMSG_AUERR (p3CMSG_AUDERR | p3CMSG_AUUERR)
#define p3CMSG_SHUTDOWN 13
#define p3CMSG_SHRIMM 0x01
#define p3CMSG_SHRTIME 0x02
#define p3CMSG_ACK_SHUTDOWN 14
#define p3CMSG_ASACK 0x01
#define p3PSS_FLG1 0x00000001
#define p3RT_IPv4 0x00000001
Typedefs
typedef struct _p3session p3session
typedef struct _p3route p3route
typedef struct _p3ctlmsg p3ctlmsg
Functions
int send_ctl_message (int type, unsigned char *message, int len, p3session *p3sess)
int recv_ctl_message (unsigned char *message)
int set_key_array (unsigned char *karray, int ksize, int dsize)
void key_array_error (int flag)
int replace_key_index (int type, int index)
int replace_key (int type, unsigned char *key, int klen)
void replace_key_error (int flag)
int rekey_test_pri (unsigned char *message, int size)
int rekey_test_sec (unsigned char *message, int size)
void rekey_session (unsigned int key_num)
int heartbeat_query (int sec, int subsec, unsigned int seqnum)
void heartbeat_answer (int sec, int subsec, unsigned int seqnum)
Variables
p3session * p3sess
Detailed Description
Protected Point to Point primary user interface header file
Copyright (C) Velocite 2010
Define Documentation
#define p3KTYPE_AES128 1
Referenced by recv_ctl_message().
#define p3KSIZE_AES128 (128 >> 3)
Referenced by recv_ctl_message().
#define p3KTYPE_AES256 2
Referenced by recv_ctl_message().
#define p3KSIZE_AES256 (256 >> 3)
Referenced by recv_ctl_message().
#define p3STYPE_DATA 1
Referenced by recv_ctl_message().
#define p3STYPE_CTL 2
Referenced by recv_ctl_message().
#define p3CMSG_KTYPE 0x0f
Referenced by recv_ctl_message().
#define p3CMSG_SET_KEY_ARRAY 1
Referenced by recv_ctl_message().
#define p3CMSG_ACK_KEY_ARRAY 2
Referenced by recv_ctl_message().
#define p3CMSG_AKKERR 0x01
#define p3CMSG_AKDERR 0x02
#define p3CMSG_AKERR (p3CMSG_AKKERR | p3CMSG_AKDERR)
Referenced by recv_ctl_message().
#define p3CMSG_REPLACE_KEY 3
Referenced by recv_ctl_message().
#define p3CMSG_KRDIDX 0x10
Referenced by recv_ctl_message().
#define p3CMSG_KRCIDX 0x20
Referenced by recv_ctl_message().
#define p3CMSG_KRXMIT 0x40
#define p3CMSG_KEY_STATUS 4
Referenced by recv_ctl_message().
#define p3CMSG_KSCKERR 0x01
#define p3CMSG_KSCIERR 0x02
#define p3CMSG_KSDKERR 0x04
#define p3CMSG_KSDIERR 0x08
#define p3CMSG_KSERR (p3CMSG_KSCKERR | p3CMSG_KSCIERR | p3CMSG_KSDKERR | p3CMSG_KSDIERR)
Referenced by recv_ctl_message().
#define p3CMSG_REKEY 5
Referenced by recv_ctl_message().
#define p3CMSG_REKEY_TEST 6
Referenced by recv_ctl_message().
#define p3CMSG_HRTBEAT_QUERY 7
Referenced by recv_ctl_message().
#define p3CMSG_HRTBEAT_ANSWER 8
Referenced by recv_ctl_message().
#define p3CMSG_STATUS_REQ 9
Referenced by recv_ctl_message().
#define p3CMSG_STATUS_RESP 10
Referenced by recv_ctl_message().
#define p3CMSG_UPDATE_INFO 11
Referenced by recv_ctl_message().
#define p3CMSG_UICODE 0x01
#define p3CMSG_UICFG 0x02
#define p3CMSG_ACK_UPDATE 12
Referenced by recv_ctl_message().
#define p3CMSG_AUDERR 0x01
#define p3CMSG_AUUERR 0x02
#define p3CMSG_AUERR (p3CMSG_AUDERR | p3CMSG_AUUERR)
#define p3CMSG_SHUTDOWN 13
Referenced by recv_ctl_message().
#define p3CMSG_SHRIMM 0x01
#define p3CMSG_SHRTIME 0x02
#define p3CMSG_ACK_SHUTDOWN 14
Referenced by recv_ctl_message().
#define p3CMSG_ASACK 0x01
#define p3PSS_FLG1 0x00000001
#define p3RT_IPv4 0x00000001
Typedef Documentation
typedef struct _p3session p3session
typedef struct _p3route p3route
typedef struct _p3ctlmsg p3ctlmsg
Function Documentation
int send_ctl_message (int type, unsigned char * message, int len, p3session * p3sess)
Function:
send_ctl_message
Description:
Manage the primary to secondary session.
NOTE: If implemented as a continuous child process, see sendmsg, recvmsg, and cmsg for passing socket file descriptors.
Inputs:
type: P3 control message type
message: Message data
len: Length of message data
sess: Session structure
Outputs:
int: Status
0 = OK
<0 = Error
References _p3session::ctlhdr, _p3session::hdrlen, and p3malloc.
int recv_ctl_message (unsigned char * message)
Function:
recv_ctl_message
Description:
Parse a message and call the function to handle it. The format of the Control Messages is:
 | 4 octets | 1 octet | Variable length |
 | Size     | Command | Data            |
   where the fields are:
 Size:  The total size of the message, including the size field itself
 Command:  An 8-bit number
 Data:  The data, if any, associated with the command
The handler functions must be defined in the primary or secondary session handler, depending on which receives the message. The message handling code is only compiled if the P3 system is the receiver. All message handling is compiled for the Primary Plus Secondary P3 system.
See the P3 System Specification for details on the commands.
Inputs:
message: The full message buffer including the size field.
Outputs:
int: Status
0 = OK
<0 = Error
>0 = Status from remote P3 system
References heartbeat_answer(), heartbeat_query(), key_array_error(), p3CMSG_ACK_KEY_ARRAY, p3CMSG_ACK_SHUTDOWN, p3CMSG_ACK_UPDATE, p3CMSG_AKERR, p3CMSG_HRTBEAT_ANSWER, p3CMSG_HRTBEAT_QUERY, p3CMSG_KEY_STATUS, p3CMSG_KRCIDX, p3CMSG_KRDIDX, p3CMSG_KSERR, p3CMSG_KTYPE, p3CMSG_REKEY, p3CMSG_REKEY_TEST, p3CMSG_REPLACE_KEY, p3CMSG_SET_KEY_ARRAY, p3CMSG_SHUTDOWN, p3CMSG_STATUS_REQ, p3CMSG_STATUS_RESP, p3CMSG_UPDATE_INFO, p3KSIZE_AES128, p3KSIZE_AES256, p3KTYPE_AES128, p3KTYPE_AES256, p3STYPE_CTL, p3STYPE_DATA, rekey_session(), rekey_test_pri(), rekey_test_sec(), replace_key(), replace_key_error(), replace_key_index(), and set_key_array().
int set_key_array (unsigned char * karray, int ksize, int dsize)
Function:
set_key_array
Description:
Receive an array of keys from the primary. The secondary stores these in an array for when an index is used to indicate the key replacement.
Inputs:
None
Outputs:
int: Status (see the errors for the p3CMSG_ACK_KEY_ARRAY field)
Referenced by recv_ctl_message().
void key_array_error (int flag)
Function:
key_array_error
Description:
Handle a key array error message from the secondary session.
Inputs:
flag: Indicates the specific error
Outputs:
None
Referenced by recv_ctl_message().
int replace_key_index (int type, int index)
Function:
replace_key_index
Description:
Replace a key using an index into the key array.
Inputs:
type: The type of key to be replaced:
Data
Control
Outputs:
int: Status (see the errors for the p3CMSG_KEY_STATUS field)
Referenced by recv_ctl_message().
int replace_key (int type, unsigned char * key, int klen)
Function:
replace_key
Description:
Replace a key from the primary using the key sent in the message.
Inputs:
type: The type of key to be replaced:
Data
Control
key: The key contained in the message
klen: The length of the key
Outputs:
int: Status (see the errors for the p3CMSG_KEY_STATUS field)
Referenced by recv_ctl_message().
void replace_key_error (int flag)
Function:
replace_key_error
Description:
Handle a key array error message from the secondary session.
Inputs:
flag: Indicates the specific error
Outputs:
None
Referenced by recv_ctl_message().
int rekey_test_pri (unsigned char * message, int size)
Function:
rekey_test_pri
Description:
Receive a message from a secondary, reverse it and compare it to the original test message.
Inputs:
message: The message from the secondary
size: The size of the message
Outputs:
int: Status
0 = OK
<0 = Error
Referenced by recv_ctl_message().
int rekey_test_sec (unsigned char * message, int size)
Function:
rekey_test_sec
Description:
Receive a message from the primary, reverse it and resend it.
Inputs:
message: The message from the primary
size: The size of the message
Outputs:
int: Status
0 = OK
<0 = Error
Referenced by recv_ctl_message().
void rekey_session (unsigned int key_num)
Function:
rekey_session
Description:
Start using a replacement key from the primary.
Inputs:
key_num: The packet ID of the first packet to use the new key
Outputs:
None
Referenced by recv_ctl_message().
int heartbeat_query (int sec, int subsec, unsigned int seqnum)
Function:
heartbeat_query
Description:
Handle a heartbeat query message from a primary.
Inputs:
sec: The number of seconds after midnight the message was sent
subsec: The sub second time the message was sent
seqnum: The sequence number of the query
Outputs:
int: Status
0 = OK
<0 = Error
Referenced by recv_ctl_message().
void heartbeat_answer (int sec, int subsec, unsigned int seqnum)
Function:
heartbeat_answer
Description:
Handle a heartbeat answer message from a secondary.
Inputs:
sec: The number of seconds after midnight the message was sent
subsec: The sub second time the message was sent
seqnum: The sequence number of the query
Outputs:
None
Referenced by recv_ctl_message().
Variable Documentation
p3session* p3sess
Global variable usage