Velocite Systems Protected Point to Point Solution: p3sec_session.c File Reference
p3sec_session.c File Reference
#include "p3session.h"
#include "p3secondary.h"
Defines
#define _p3SEC_SS_C
Functions
int init_sec_session ()
int sec_session_manager ()
int set_key_array (unsigned char *message, int ksize, int dsize)
int replace_key_index (int type, int index)
int replace_key (int type, unsigned char *key, int klen)
void rekey_session (unsigned int key_num)
int rekey_test_sec (unsigned char *message, int size)
int heartbeat_query (int sec, int subsec, unsigned int seqnum)
Variables
p3session * p3sess
Detailed Description
Protected Point to Point secondary session
Copyright (C) Velocite 2010
The secondary user session manages communications with primary P3 systems.
Define Documentation
#define _p3SEC_SS_C
Function Documentation
int init_sec_session ()
Function:
init_sec_session
Description:
Initialize the secondary to primary session.
Inputs:
None
Outputs:
int: Status
0 = OK
<0 = Error
References p3buf, p3calloc, p3errmsg(), and p3MSG_CRIT.
int sec_session_manager ()
Function:
session_manager
Description:
Manage the secondary to secondary session.
NOTE: If implemented as a continuous child process, see sendmsg, recvmsg, and cmsg for passing socket file descriptors.
Inputs:
None
Outputs:
int: Status
0 = OK
<0 = Error
int set_key_array (unsigned char * message, int ksize, int dsize)
Function:
set_key_array
Description:
Receive an array of keys from the primary. The secondary stores these in an array for when an index is used to indicate the key replacement.
Inputs:
None
Outputs:
int: Status (see the errors for the p3CMSG_ACK_KEY_ARRAY field)
Referenced by recv_ctl_message().
int replace_key_index (int type, int index)
Function:
replace_key_index
Description:
Replace a key using an index into the key array.
Inputs:
type: The type of key to be replaced:
Data
Control
Outputs:
int: Status (see the errors for the p3CMSG_KEY_STATUS field)
Referenced by recv_ctl_message().
int replace_key (int type, unsigned char * key, int klen)
Function:
replace_key
Description:
Replace a key from the primary using the key sent in the message.
Inputs:
type: The type of key to be replaced:
Data
Control
key: The key contained in the message
klen: The length of the key
Outputs:
int: Status (see the errors for the p3CMSG_KEY_STATUS field)
Referenced by recv_ctl_message().
void rekey_session (unsigned int key_num)
Function:
rekey_session
Description:
Start using a replacement key from the primary.
Inputs:
key_num: The packet ID of the first packet to use the new key
Outputs:
None
Referenced by recv_ctl_message().
int rekey_test_sec (unsigned char * message, int size)
Function:
rekey_test_sec
Description:
Receive a message from the primary, reverse it and resend it.
Inputs:
message: The message from the primary
size: The size of the message
Outputs:
int: Status
0 = OK
<0 = Error
Referenced by recv_ctl_message().
int heartbeat_query (int sec, int subsec, unsigned int seqnum)
Function:
heartbeat_query
Description:
Handle a heartbeat query message from a primary.
Inputs:
sec: The number of seconds after midnight the message was sent
subsec: The sub second time the message was sent
seqnum: The sequence number of the query
Outputs:
int: Status
0 = OK
<0 = Error
Referenced by recv_ctl_message().
Variable Documentation
p3session* p3sess
Global variable usage