Velocite Systems Protected Point to Point Solution: p3utils.h File Reference
p3utils.h File Reference
Detailed Description
Protected Point to Point utils header file
Copyright (C) Velocite 2010
#include "p3base.h"
#include <netinet/ip.h>
#include <netinet/ip6.h>
Data Structures
struct _p3util
struct _p3mm_anchor
struct _p3cluster
struct _p3chost
Defines
#define P3DEVNAME "/dev/p3dev"
#define P3IOC_TYPE 'p'
#define P3_IOW(type, nr, size) _IOC(_IOC_WRITE,(type),(nr),size)
#define P3_IOR(type, nr, size) _IOC(_IOC_READ, (type),(nr),size)
#define RAMDISK_SZ 0x1000
#define MM_CMD_INIT "PID"
#define p3UTL_NINFO 0x00000001
#define p3UTL_NWARN 0x00000002
#define p3CLS_LB_RR 0x00000001
#define p3CLS_LB_BC 0x00000002
#define p3CLS_IREC 0x00000004
#define p3CHS_PRI 0x00000001
#define MM_READ_ERR(buffer, size, count) if (p3utils->anchor == NULL || (count = read (p3utils->anchor->fd, buffer, size)) < 0)
#define MM_WRITE_ERR(buffer, size) if (p3utils->anchor == NULL || write(p3utils->anchor->fd, buffer, size) < 0)
Typedefs
typedef struct _p3util p3util
typedef struct _p3mm_anchor p3mm_anchor
typedef struct _p3cluster p3cluster
typedef struct _p3chost p3chost
Functions
int init_utils ()
int init_kernel_comm ()
int init_raw_socket ()
int send_ioctl (unsigned char *buffer, int size)
int receive_ioctl (unsigned char *buffer, int size)
void p3errmsg (int type, char *message)
int isallnum (char *parm)
Variables
p3util * p3utils
Define Documentation
#define P3DEVNAME "/dev/p3dev"
Referenced by init_kernel_comm().
#define P3IOC_TYPE 'p'
Referenced by receive_ioctl(), and send_ioctl().
#define P3_IOW (type, nr, size) _IOC(_IOC_WRITE,(type),(nr),size)
Referenced by send_ioctl().
#define P3_IOR (type, nr, size) _IOC(_IOC_READ, (type),(nr),size)
Referenced by receive_ioctl().
#define RAMDISK_SZ 0x1000
Referenced by init_kernel_comm().
#define MM_CMD_INIT "PID"
#define p3UTL_NINFO 0x00000001
Referenced by p3errmsg(), priplus_parse_cmdline(), and sec_parse_cmdline().
#define p3UTL_NWARN 0x00000002
#define p3CLS_LB_RR 0x00000001
#define p3CLS_LB_BC 0x00000002
#define p3CLS_IREC 0x00000004
#define p3CHS_PRI 0x00000001
#define MM_READ_ERR (buffer, size, count) if (p3utils->anchor == NULL || (count = read (p3utils->anchor->fd, buffer, size)) < 0)
Macro: MM_READ_ERR
Description:
If the mmap anchor has not been allocated or there is an error reading from the RAM disk, then the caller must handle the error. Otherwise, the amount a data read is returned.
Parameters:
buffer: An allocated buffer space.
size: The amount of data to read, which must be less than or equal to the size of the buffer space.
count: The amount of data successfully read.
#define MM_WRITE_ERR (buffer, size) if (p3utils->anchor == NULL || write(p3utils->anchor->fd, buffer, size) < 0)
Macro: MM_WRITE_ERR
Description:
If the mmap anchor has not been allocated or there is an error writing to the RAM disk, then the caller must handle the error.
Parameters:
buffer: The buffer of data to write.
size: The amount of data to write, which must be less than or equal to the size of the buffer space.
Typedef Documentation
typedef struct _p3util p3util
typedef struct _p3mm_anchor p3mm_anchor
typedef struct _p3cluster p3cluster
typedef struct _p3chost p3chost
Function Documentation
int init_utils ()
Function:
init_utils
Description:
Initialize utilities for the P3 system.
Inputs:
None
Outputs:
int: Status
0 = OK
<0 = Error
References _p3util::anchor, NULL, and p3calloc.
Referenced by main().
int init_kernel_comm ()
Function:
init_kernel_comm
Description:
Initialize the buffer used for communication with the kernel module.
NOTE: The init_key_serv function is only called by a primary to initialize the circular buffer for random numbers.
Inputs:
None
Outputs:
int: Status
0 = OK
<0 = Error
References _p3util::anchor, _p3mm_anchor::fd, init_key_serv(), NULL, p3buf, P3DEVNAME, p3errmsg(), p3MSG_CRIT, _p3mm_anchor::pid, and RAMDISK_SZ.
Referenced by main().
int init_raw_socket ()
int send_ioctl (unsigned char * buffer, int size)
Function:
send_ioctl
Description:
Send a buffer to the kernel module using an ioctl command.
Inputs:
buffer: The data to be sent.
size: The size of the data buffer.
Outputs:
int: Status
0 = OK
<0 = Error
References _p3util::anchor, _p3mm_anchor::fd, P3_IOW, p3buf, p3errmsg(), P3IOC_TYPE, and p3MSG_CRIT.
Referenced by pri_parse_config(), sec_parse_config(), update_prihost(), and update_sechost().
int receive_ioctl (unsigned char * buffer, int size)
Function:
receive_ioctl
Description:
Send a buffer to the kernel module using an ioctl command.
Inputs:
buffer: The data to be sent.
size: The size of the data buffer.
Outputs:
int: Status
0 = OK
<0 = Error
References _p3util::anchor, _p3mm_anchor::fd, P3_IOR, p3buf, p3errmsg(), P3IOC_TYPE, and p3MSG_CRIT.
void p3errmsg (int type, char * message)
Function:
p3errmsg
Description:
Handle error messages for the P3 system. The types of messages are defined in the p3base.h include file. They are:
Critical: Caused by system errors
Error: Caused by application errors
Warning: Does not cause application shutdown, but indicate the need for adminstrative correction
Notice: Information that is always reported, such as startup
Information: Information such as usage statistics. This may be ignored using the -I command line argument
Inputs:
type: The type of the message
message: The text of the message
Outputs:
None
Function:
p3errmsg
Description:
Handle error messages for the P3 system. The types of messages are defined in the p3kbase.h include file. They are:
Critical: Caused by system errors
Error: Caused by application errors
Warning: Does not cause application shutdown, but indicate the need for adminstrative correction
Notice: Information that is always reported, such as startup
Information: Information such as usage statistics. This may be ignored using the -I command line argument
Inputs:
type: The type of the message
message: The text of the message
Outputs:
None
int isallnum (char * parm)
Function:
isallnum
Description:
Validate that a string is only base 10 digits.
Inputs:
parm: The string to be tested.
Outputs:
int: Status
0 = Only digits
<0 = String contains non-digits
Variable Documentation
p3util* p3utils
Global utilities structure
Referenced by pri_parse_config(), priplus_parse_cmdline(), sec_parse_cmdline(), and sec_parse_config().