Velocite Systems Protected Point to Point Solution: p3utils.c File Reference
p3utils.c File Reference
Detailed Description
Protected Point to Point utils file
Copyright (C) Velocite 2010
Overview of the purpose of the functions in the source file.
#include "p3utils.h"
#include "p3share.h"
Defines
#define _p3_UTILS_C
Functions
int init_utils ()
int init_kernel_comm ()
int init_raw_socket (int ipver)
int send_ioctl (unsigned char *buffer, int size)
int receive_ioctl (unsigned char *buffer, int size)
void p3errmsg (int type, char *message)
int isallnum (char *parm)
p3subnetcfg * getsubnetcfg ()
Variables
p3util * p3utils
Define Documentation
#define _p3_UTILS_C
Function Documentation
int init_utils ()
Function:
init_utils
Description:
Initialize utilities for the P3 system.
Inputs:
None
Outputs:
int: Status
0 = OK
<0 = Error
References _p3util::anchor, NULL, and p3calloc.
Referenced by main().
int init_kernel_comm ()
Function:
init_kernel_comm
Description:
Initialize the buffer used for communication with the kernel module.
NOTE: The init_key_serv function is only called by a primary to initialize the circular buffer for random numbers.
Inputs:
None
Outputs:
int: Status
0 = OK
<0 = Error
References _p3util::anchor, _p3mm_anchor::fd, init_key_serv(), NULL, p3buf, P3DEVNAME, p3errmsg(), p3MSG_CRIT, _p3mm_anchor::pid, and RAMDISK_SZ.
Referenced by main().
int init_raw_socket (int ipver)
Function:
init_raw_socket
Description:
Initialize the Raw socket used by the kernel module to send control messages.
Inputs:
ipver: The IP version of the interface to be used for the Raw socket.
Outputs:
int: Status
0 = OK
<0 = Error
References _p3util::lochost, p3buf, p3errmsg(), p3MSG_CRIT, p3MSG_DEBUG, _p3util::remhost, and _p3util::v4.
Referenced by main().
int send_ioctl (unsigned char * buffer, int size)
Function:
send_ioctl
Description:
Send a buffer to the kernel module using an ioctl command.
Inputs:
buffer: The data to be sent.
size: The size of the data buffer.
Outputs:
int: Status
0 = OK
<0 = Error
References _p3util::anchor, _p3mm_anchor::fd, P3_IOW, p3buf, p3errmsg(), P3IOC_TYPE, and p3MSG_CRIT.
Referenced by pri_parse_config(), sec_parse_config(), update_prihost(), and update_sechost().
int receive_ioctl (unsigned char * buffer, int size)
Function:
receive_ioctl
Description:
Send a buffer to the kernel module using an ioctl command.
Inputs:
buffer: The data to be sent.
size: The size of the data buffer.
Outputs:
int: Status
0 = OK
<0 = Error
References _p3util::anchor, _p3mm_anchor::fd, P3_IOR, p3buf, p3errmsg(), P3IOC_TYPE, and p3MSG_CRIT.
void p3errmsg (int type, char * message)
Function:
p3errmsg
Description:
Handle error messages for the P3 system. The types of messages are defined in the p3base.h include file. They are:
Critical: Caused by system errors
Error: Caused by application errors
Warning: Does not cause application shutdown, but indicate the need for adminstrative correction
Notice: Information that is always reported, such as startup
Information: Information such as usage statistics. This may be ignored using the -I command line argument
Inputs:
type: The type of the message
message: The text of the message
Outputs:
None
int isallnum (char * parm)
Function:
isallnum
Description:
Validate that a string is only base 10 digits.
Inputs:
parm: The string to be tested.
Outputs:
int: Status
0 = Only digits
<0 = String contains non-digits
Referenced by main(), pri_parse_config(), and sec_parse_config().
p3subnetcfg* getsubnetcfg ()
Function:
getsubnetcfg
Description:
Allocate a subnet configuration structure and initialize to all zeros.
Inputs:
None.
Outputs:
p3subnetcfg *: The new subnet configuration structure or NULL if there is an error.
References NULL, p3buf, p3calloc, p3errmsg(), and p3MSG_CRIT.
Referenced by pri_parse_config(), and sec_parse_config().
Variable Documentation
p3util* p3utils
Global utilities structure
Referenced by pri_parse_config(), priplus_parse_cmdline(), sec_parse_cmdline(), and sec_parse_config().