Velocite Systems Protected Point to Point Solution: aesCipherContext Struct Reference
aesCipherContext Struct Reference
#include <aes.h>
Data Fields
sbyte4 encrypt
sbyte4 mode
sbyte4 keyLen
sbyte4 Nr
ubyte4 rk [4 *(AES_MAXNR+1)]
ubyte4 ek [4 *(AES_MAXNR+1)]
Field Documentation
sbyte4 aesCipherContext::encrypt
Referenced by AESALGO_blockDecrypt(), AESALGO_blockEncrypt(), and AESALGO_makeAesKey().
sbyte4 aesCipherContext::mode
Referenced by AESALGO_blockDecrypt(), AESALGO_blockEncrypt(), and AESALGO_makeAesKey().
sbyte4 aesCipherContext::keyLen
Referenced by AESALGO_makeAesKey().
sbyte4 aesCipherContext::Nr
Referenced by AES_XCBC_MAC_96_update(), AESALGO_blockDecrypt(), AESALGO_blockEncrypt(), and AESALGO_makeAesKey().
ubyte4 aesCipherContext::rk[4 *(AES_MAXNR+1)]
Referenced by AES_XCBC_MAC_96_update(), AESALGO_blockDecrypt(), AESALGO_blockEncrypt(), and AESALGO_makeAesKey().
ubyte4 aesCipherContext::ek[4 *(AES_MAXNR+1)]
Referenced by AESALGO_blockDecrypt(), AESALGO_blockEncrypt(), and AESALGO_makeAesKey().
The documentation for this struct was generated from the following file:
aes.h