Velocite Systems Protected Point to Point Solution: tmp_net_mgmt.c File Reference
tmp_net_mgmt.c File Reference
#include "tmp.h"
Defines
#define _tmp_NET_MGMT_C 1
Functions
int tmp_listen (int sl_type, tmpNetwork *sl_net)
int tmp_listener (int ls_sd, tmpNetwork *ls_net, tmpNetwork *ls_hostlist)
int tmp_session (int ss_type, tmpNetwork *ss_net)
int tmp_net_transmit (tmpNetwork *ns_net)
int tmp_net_receive (tmpNetwork *nr_net)
int tmp_nstat (tmpNetwork *ns_net)
Variables
char msg_tbuf [1024]
char * tmp_emsg
char * nm_msgq [tmpNET_MSG_MAX]
int nm_midx = 0
int nm_pidx = 0
Define Documentation
#define _tmp_NET_MGMT_C 1
Temporary network management.
Function Documentation
int tmp_listen (int sl_type, tmpNetwork * sl_net)
Open a socket for listening
Inputs:
sl_type: Operation type
Types:
tmpSTART: Attempt to open a socket for listening
tmpSTOP: Close a listeners socket
sl_net: Network structure defining local host
Outputs:
stat: Status
0 = OK
<0 = Error
>0 = Informational
References _tmpNetwork::flag, _tmpNetwork::host, msg_tbuf, nm_midx, _tmpNetwork::port, _tmpNetwork::sd, _tmpNetwork::ss, tmpNET_MESSAGE, tmpNET_V4ONLY, tmpNET_V6ONLY, tmpSTART, and tmpSTOP.
Referenced by handle_shutdown(), main(), and register_pcap().
int tmp_listener (int ls_sd, tmpNetwork * ls_net, tmpNetwork * ls_hostlist)
Function: tmp_listener
Description:
Accept or reject listen requests
Inputs:
ls_sd: Socket descriptor of connection request
ls_net: Network structure of local host
ls_hostlist: List of allowed remote hosts
Outputs:
stat: Status
0 = OK
<0 = Error
>0 = New socket descriptor for host
ls_net->flag & tmpNET_ERRNO = errno if applicable
References _tmpNetwork::addr, _tmpNetwork::flag, msg_tbuf, _tmpNetwork::next, nm_midx, _tmpNetwork::sd, _tmpNetwork::ss, tmp_nstat(), tmpNET_ERRNO, tmpNET_KPALIVE, tmpNET_MESSAGE, tmpNET_NOBLK, tmpNET_ST_DISC, tmpNET_ST_NEW, and tmpNET_ST_UP.
Referenced by main(), and register_pcap().
int tmp_session (int ss_type, tmpNetwork * ss_net)
Function: tmp_session
Description:
Establish a session with a remote host
Inputs:
ss_type: Operation type
tmpSTART: Attempt to establish a session
tmpSTOP: Disconnect a session
ss_net: Network information structure
Outputs:
stat: Status
0 = OK
<0 = Error
>0 = Informational
References _tmpNetwork::addr, _tmpNetwork::flag, _tmpNetwork::host, msg_tbuf, nm_midx, _tmpNetwork::port, _tmpNetwork::sd, _tmpNetwork::ss, tmpNET_MESSAGE, tmpNET_ST_NEW, tmpNET_ST_UP, tmpNET_V4ONLY, tmpNET_V6ONLY, tmpSTART, and tmpSTOP.
Referenced by connect_primary(), handle_shutdown(), handle_shutdownSEC(), main(), tmp_net_receive(), tmp_net_transmit(), and tmp_nstat().
int tmp_net_transmit (tmpNetwork * ns_net)
Function: tmp_net_transmit
Description
Send buffered data
Inputs:
ns_net: Network structure for remote host connection
Outputs:
stat: Status
0 = OK
<0 = Error
>0 = Informational
References _tmpNetData::buffer, _tmpNetwork::dataout, _tmpNetwork::dataoutl, _tmpNetwork::flag, freeNET_DATA, _tmpNetData::idx, msg_tbuf, _tmpNetData::next, nm_midx, _tmpNetwork::sd, _tmpNetData::size, tmp_nstat(), tmp_session(), tmpINIT_WAIT, tmpNET_BUFSZ, tmpNET_INCMPLT, tmpNET_MESSAGE, and tmpSTOP.
Referenced by main().
int tmp_net_receive (tmpNetwork * nr_net)
Function: tmp_net_receive
Description
Receive data into component buffers
Inputs:
nr_net: Network structure for remote host connection
Outputs:
stat: Status
0 = OK
<0 = Error
References _tmpNetData::buffer, _tmpNetwork::datain, _tmpNetwork::datainl, _tmpNetwork::flag, msg_tbuf, _tmpNetData::next, nm_midx, _tmpNetwork::sd, _tmpNetData::size, tmp_nstat(), tmp_session(), tmpINIT_WAIT, tmpMICROSEC, tmpNET_1BUF, tmpNET_BUFSZ, tmpNET_MESSAGE, tmpRECV_SZ, tmpSET_WAIT, and tmpSTOP.
Referenced by main().
int tmp_nstat (tmpNetwork * ns_net)
Function: tmp_nstat
Description
Receive data into component buffers
Inputs:
ns_net: Network structure for remote host connection
Outputs:
stat: Status
0 = OK
<0 = Error
References msg_tbuf, _tmpNetwork::sd, tmp_session(), tmpNET_MESSAGE, and tmpSTOP.
Referenced by main(), tmp_listener(), tmp_net_receive(), and tmp_net_transmit().
Variable Documentation
char msg_tbuf[1024]
Temporary buffer for network management
Referenced by tmp_listen(), tmp_listener(), tmp_net_receive(), tmp_net_transmit(), tmp_nstat(), and tmp_session().
char* tmp_emsg
String pointer for memory messages
char* nm_msgq[tmpNET_MSG_MAX]
Network message queue
Referenced by connect_primary(), main(), and register_pcap().
int nm_midx = 0
Index of network message queue
Referenced by connect_primary(), main(), register_pcap(), tmp_listen(), tmp_listener(), tmp_net_receive(), tmp_net_transmit(), and tmp_session().
int nm_pidx = 0
Index of network message queue