Velocite Systems Protected Point to Point Solution: tmp_xserver.c File Reference
tmp_xserver.c File Reference
#include "p3base.h"
#include "tmp_net_mgmt.h"
Functions
void handle_shutdown (int hs_sig)
int main (int argc, char *argv[])
Variables
unsigned char * tmp3resp = NULL
Function Documentation
void handle_shutdown (int hs_sig)
int main (int argc, char * argv[])
References _tmpNetData::buffer, DATAFILE, freeNET_DATA, handle_shutdown(), _tmpNetData::next, nm_midx, nm_msgq, _tmpNetData::size, tmp3net, tmp3resp, tmp_listen(), tmp_listener(), tmp_net_receive(), tmp_net_transmit(), tmp_nstat(), tmp_session(), tmpNET_1BUF, tmpNET_BUFSZ, tmpNET_V4ONLY, tmpSTART, and tmpSTOP.
Variable Documentation
unsigned char* tmp3resp = NULL
Referenced by main().