Velocite Systems Protected Point to Point Solution: tmpPrimary.c File Reference
tmpPrimary.c File Reference
#include "p3base.h"
#include "tmp.h"
Defines
#define _p3TEMP_PRIMARY_C
Functions
void handle_shutdown (int hs_sig)
tmpNetwork * register_pcap ()
Variables
tmpNetwork * tmp3net = NULL
Define Documentation
#define _p3TEMP_PRIMARY_C
Temporary functions for proof of concept.
Function Documentation
void handle_shutdown (int hs_sig)
References tmp_listen(), tmp_session(), and tmpSTOP.
Referenced by main(), and register_pcap().
tmpNetwork* register_pcap ()
Listen for connection request. Return network structure or NULL if error.
References _tmpNetwork::addr, _tmpNetwork::flag, handle_shutdown(), _tmpNetwork::host, nm_midx, nm_msgq, _tmpNetwork::port, _tmpNetwork::sd, tmp_listen(), tmp_listener(), tmpNET_V4ONLY, tmpP3ADDR, tmpP3NAME, tmpP3PORT, tmpSTART, and tmpSTOP.
Referenced by init_pri_net().
Variable Documentation
tmpNetwork* tmp3net = NULL
Referenced by main().