Velocite Systems Protected Point to Point Solution: tmpSecondary.c File Reference
tmpSecondary.c File Reference
#include "tmp.h"
Defines
#define _p3TEMP_SECONDARY_C
Functions
void handle_shutdownSEC (int hs_sig)
int connect_primary ()
Variables
tmpNetwork * p3pri = NULL
Define Documentation
#define _p3TEMP_SECONDARY_C
Temporary functions for proof of concept.
Function Documentation
void handle_shutdownSEC (int hs_sig)
References tmp_session(), and tmpSTOP.
Referenced by connect_primary().
int connect_primary ()
Make a connection request to the primary. Return stat:
0 = OK
<0 = Connection failed
References _tmpNetwork::addr, _tmpNetwork::flag, handle_shutdownSEC(), _tmpNetwork::host, nm_midx, nm_msgq, _tmpNetwork::port, tmp_session(), tmpNET_V4ONLY, tmpP3ADDR, tmpP3NAME, tmpP3PORT, and tmpSTART.
Referenced by init_sec_net().
Variable Documentation
tmpNetwork* p3pri = NULL